### ISSUE TITLE
migrate tsd => typings

### ISSUE THREAD

**Issue by BugsBunnyBR** [lathonez/clicker#10]
It says tsd is deprecated...
https://github.com/DefinitelyTyped/tsd/issues/269

and in the ionic changelog to beta1:

**angular 2.0.0-beta.6**: if you are using typescript, update the following: 
https://github.com/driftyco/ionic-conference-app/commit/26f3393fe4be78468e1c51e0bbf5d05a2666cd20

How about a migration to typings?

**Comment by lathonez** [comment]
I actually tried this but couldn't get it to work non-interactively, which is a problem for me (wrt Travis).

I didn't try very hard, will have another go.

**Comment by BugsBunnyBR** [comment]
:clap:
