### ISSUE TITLE
I replaced --ambient with --global popups another error 

### ISSUE THREAD

**Issue by yokeshvaradhan** [lathonez/clicker#101]
I replaced --ambient with --global now i get a different error **"Unable to find "node" ("npm") in the registry."**

I am trying to install all the dependency from this link _http://lathonez.github.io/2016/ionic-2-e2e-testing/_
but i could not install this  _**"typings install --ambient --save angular-protractor jasmine node selenium-webdriver"**_

**Comment by lathonez** [comment]
If you check the tutorial, the command you should be using to install
typings is:

typings install --save --global registry:dt/jasmine registry:dt/node

**Comment by lathonez** [comment]
Just realised the e2e tutorial is not up to date. Apologies will sort it tonight.

The above should help you get going

**Comment by yokeshvaradhan** [comment]
thank you it worked
