### ISSUE TITLE
Setup has changed: static and dynamic platform testing

### ISSUE THREAD

**Issue by m5rk** [lathonez/clicker#105]
This [PR](https://github.com/angular/angular/pull/8739) breaks the setup documented in [your unit testing walkthrough](http://lathonez.github.io/2016/ionic-2-unit-testing/).

**Comment by lathonez** [comment]
Thanks for raising. What's the problem exactly?

**Comment by m5rk** [comment]
In short, if you follow the walkthrough with the latest angular, it won't work because the module structure changed. I used this and it works:

```typescript
import { setBaseTestProviders } from '@angular/core/testing';
import {
  TEST_BROWSER_DYNAMIC_APPLICATION_PROVIDERS,
  TEST_BROWSER_DYNAMIC_PLATFORM_PROVIDERS,
} from '@angular/platform-browser-dynamic/testing';

setBaseTestProviders(TEST_BROWSER_DYNAMIC_PLATFORM_PROVIDERS, TEST_BROWSER_DYNAMIC_APPLICATION_PROVIDERS);
```

**Comment by lathonez** [comment]
I've made [this change](https://github.com/lathonez/lathonez.github.io/commit/9beed71c32eb67ccd8471c73588a4388bc33122f) which brings the blog in line with the working code in this repo.

What version of angular are you using? ionic are still on .rc1 and I don't move ahead of those guys, more trouble than it's worth.

**Comment by m5rk** [comment]
I'm using `2.0.0-rc.1`

**Comment by lathonez** [comment]
Sweet, in which case the above change should sort it.

**Comment by lathonez** [comment]
Thanks again for raising this @m5rk

**Comment by m5rk** [comment]
Your blog articles have saved me a ton of time. I appreciate what you're doing.
