### ISSUE TITLE
no-constructor-vars breaks DI

### ISSUE THREAD

**Issue by m5rk** [lathonez/clicker#106]
I copied the `tslint.json` from this repository and updated my code to conform to the rules. That seemed to break my app. If I declare a provider in the ionicBootraps function:

```typescript
ionicBootstrap(MyApp, [Authentication]);
```

but then declare its visibility like so:

```typescript
export class MyClass {
  private auth: Authentication;

  constructor(auth: Authentication) {
  }
```

MyClass's auth is `undefined`. Whereas if I do this instead:

```typescript
export class MyClass {
  constructor(private auth: Authentication) {
  }
```

It Just Works™.

**Comment by lathonez** [comment]
You need to set the class's instance of auth to the one passed in the constructor:

```javascript

export class MyClass {
  private auth: Authentication;

  constructor(auth: Authentication) {
    this.auth = auth;
  }
```

Please reopen if this doesn't work.

**Comment by m5rk** [comment]
That works. Thank you for the quick reply.

I'm left with this question:  Which is better--[not manually assigning constructor parameters](https://www.stevefenton.co.uk/2013/04/stop-manually-assigning-typescript-constructor-parameters/) or not declaring parameters in the constructor?

**Comment by m5rk** [comment]
Based on the way Ionic 2 generates classes, I think they've answered that question a certain way.

**Comment by lathonez** [comment]
IMO explicit is better than implicit.

When you implicitly declare in the constructor it isn't clear that those variables are being assigned to the class (`this`), hence your confusion when your removed the `private` and found that it was no longer assigned.

It's all very subjective, but I think clearer is better.

**Comment by lathonez** [comment]
#191
