### ISSUE TITLE
Cannot find module '@angular/platform-browser/testing/browser_static'

### ISSUE THREAD

**Issue by rtm** [lathonez/clicker#107]
This is occurring with 

    @angular/platform-browser": "^2.0.0-rc.1"

**Comment by lathonez** [comment]
Is this from following the blog or are you getting this running npm test against the project?

If the former case, does Marks suggestion from #105 help you?

**Comment by rtm** [comment]
Solved, thanks.

**Comment by lathonez** [comment]
#191
