### ISSUE TITLE
Test cases failing

### ISSUE THREAD

**Issue by geoHeil** [lathonez/clicker#111]
Hi `npm test` works fine on osx, but on Ubuntu it is failing with the following error:

```
Requiring external module ts-node/register
TSError: ⨯ Unable to compile TypeScript
test/gulpfile.ts (1,22): Cannot find module 'path'. (2307)
test/gulpfile.ts (4,9): Cannot find name 'require'. (2304)
test/gulpfile.ts (12,9): Cannot find name 'require'. (2304)
test/gulpfile.ts (13,16): Cannot find name 'require'. (2304)
test/gulpfile.ts (14,18): Cannot find name 'require'. (2304)
test/gulpfile.ts (14,31): Cannot find name 'process'. (2304)
test/gulpfile.ts (30,25): Cannot find name 'require'. (2304)
test/gulpfile.ts (46,18): Cannot find name 'require'. (2304)
test/gulpfile.ts (57,20): Cannot find name 'require'. (2304)
test/gulpfile.ts (59,22): Cannot find name 'process'. (2304)
test/gulpfile.ts (69,20): Cannot find name 'require'. (2304)
test/gulpfile.ts (71,22): Cannot find name 'process'. (2304)
test/gulpfile.ts (82,21): Cannot find name 'require'. (2304)
    at getOutput (/clicker/node_modules/ts-node/src/index.ts:280:15)
    at compile (/clicker/node_modules/ts-node/src/index.ts:289:14)
    at loader (/clicker/node_modules/ts-node/src/index.ts:304:23)
    at Object.require.extensions.(anonymous function) [as .ts] (/clicker/node_modules/ts-node/src/index.ts:321:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/clicker/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/clicker/node_modules/gulp/node_modules/liftoff/index.js:193:16)
```

Here is a dockerfile https://gist.github.com/geoHeil/48cd94bf4d748fd8fd6d25de4c272157 which demonstrates a linux environment which leads to this error.

**Comment by lathonez** [comment]
@geoHeil our [CI builds](https://travis-ci.org/lathonez/clicker/builds/141222909) are on Ubuntu 14.04 and I run arch, so it's unlikely to be a linux or ubuntu specific issue.

The above error is the typescript compiler not being able to find the node typiings:

```
x220:~/code/clicker$ grep node typings.json 
    "node": "registry:dt/node#6.0.0+20160514165920",
```

I'll have a look with the docker file you've provided later on

**Comment by lathonez** [comment]
replicated using the dockerfile provided

**Comment by lathonez** [comment]
I just had to run `typings install` as a separate step, so for some reason the post install hook is failing in your setup:

```
    "postinstall": "ionic state restore && typings install && webdriver-manager update && cp test/karma-static/*.html node_modules/karma/static",
```

**Comment by lathonez** [comment]
`npm WARN cannot run in wd clicker@1.8.0 ionic state restore && typings install && webdriver-manager update && cp test/karma-static/*.html node_modules/karma/static (wd=/clicker)`

**Comment by lathonez** [comment]
Possibly relevant:

http://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd

**Comment by lathonez** [comment]
`npm install --unsafe-perms`

did not work

**Comment by geoHeil** [comment]
Thanks a lot.

**Comment by lathonez** [comment]
Adding `--allow-root-install` to the [postinstall line](https://github.com/lathonez/clicker/blob/master/package.json#L66) does the trick:

```
"postinstall": "ionic state restore && typings install && webdriver-manager update && cp test/karma-static/*.html node_modules/karma/static --allow-root-install",
```

I'm not keen to put this in the repo as default as I'm not clear on the consequences of doing so. I don't think it's good practice to run anything as root (even in docker).

I will however put something in the readme and link this issue from the blog.

**Comment by geoHeil** [comment]
Nope you are right. I will change the docker file.

**Comment by lathonez** [comment]
Sweet, closing

**Comment by lathonez** [comment]
#191
