### ISSUE TITLE
Failed: Uncaught (in promise): cordova_not_available

### ISSUE THREAD

**Issue by srishiva89** [lathonez/clicker#116]
When I'm running npm test, I'm getting "Failed: Uncaught (in promise): cordova_not_available" error.

```
A:\project\dx2>npm test

Diagnox@1.0.1 test A:\project\dx2
gulp --gulpfile test/gulpfile.ts --cwd ./ unit-test
[00:37:15] Requiring external module ts-node/register
[00:37:18] Using gulpfile A:\project\dx2\test\gulpfile.ts
[00:37:18] Starting 'unit-test'...
[00:37:18] Starting 'lint'...
[00:37:18] Starting 'html'...
[00:37:18] Finished 'html' after 561 ms
[00:37:18] Finished 'lint' after 925 ms
[00:37:19] Starting 'karma'...
decorator { '0': [Function], '1': 0, '2': true, '3': undefined }

START:
04 07 2016 00:37:33.256:INFO [framework.browserify]: bundle built
04 07 2016 00:37:33.290:INFO [karma]: Karma v1.1.0 server started at http://localhost:9876/
04 07 2016 00:37:33.291:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
04 07 2016 00:37:33.302:INFO [launcher]: Starting browser PhantomJS
04 07 2016 00:37:34.906:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket /#i-dJ9QVwBsRB9BqzAAAA with id 76578075
DxApp
√ initialises with an app
√ initialises with a root page
√ initialises with two pages
√ opens a page
DashboardPage
√ initialises
LabsPage
× initialises
× should get a list of labs
× should use an HTTP call to obtain a lab data
Utils
√ resets a control

Finished in 1.906 secs / 1.898 secs

SUMMARY:
√ 6 tests completed
× 3 tests failed

FAILED TESTS:
LabsPage
× initialises
PhantomJS 2.1.1 (Windows 8 0.0.0)
Failed: Uncaught (in promise): cordova_not_available

× should get a list of labs
  PhantomJS 2.1.1 (Windows 8 0.0.0)
Failed: Uncaught (in promise): cordova_not_available

× should use an HTTP call to obtain a lab data
  PhantomJS 2.1.1 (Windows 8 0.0.0)
Failed: Uncaught (in promise): cordova_not_available
------------------------------|----------|----------|----------|----------|----------------|
File | % Stmts | % Branch | % Funcs | % Lines |Uncovered Lines |
------------------------------|----------|----------|----------|----------|----------------|
app\ | 100 | 100 | 100 | 100 | |
app.ts | 100 | 100 | 100 | 100 | |
app\pages\dashboard\ | 100 | 100 | 100 | 100 | |
dashboard.ts | 100 | 100 | 100 | 100 | |
app\pages\labs\ | 88.24 | 100 | 66.67 | 81.82 | |
labs.ts | 88.24 | 100 | 66.67 | 81.82 | 29,30,32,34 |
app\providers\labs-provider\ | 91.67 | 100 | 66.67 | 91.67 | |
labs-provider.ts | 91.67 | 100 | 66.67 | 91.67 | 16 |
app\services\ | 80 | 100 | 40 | 83.33 | |
utils.ts | 80 | 100 | 40 | 83.33 | 8,10 |
------------------------------|----------|----------|----------|----------|----------------|
All files | 92.91 | 100 | 74.19 | 91.03 | |
------------------------------|----------|----------|----------|----------|----------------|

[00:37:37] 'karma' errored after 19 s
[00:37:37] Error: 1
at formatError (A:\project\dx2\node_modules\gulp\bin\gulp.js:169:10)
at Gulp. (A:\project\dx2\node_modules\gulp\bin\gulp.js:195:15)
at emitOne (events.js:82:20)
at Gulp.emit (events.js:169:7)
at Gulp.Orchestrator._emitTaskDone (A:\project\dx2\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
at A:\project\dx2\node_modules\gulp\node_modules\orchestrator\index.js:275:23
at finish (A:\project\dx2\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
at cb (A:\project\dx2\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
at removeAllListeners (A:\project\dx2\node_modules\karma\lib\server.js:379:7)
at Server. (A:\project\dx2\node_modules\karma\lib\server.js:390:9)
at Server.g (events.js:260:16)
at emitNone (events.js:72:20)
at Server.emit (events.js:166:7)
at emitCloseNT (net.js:1521:8)
at nextTickCallbackWith1Arg (node.js:431:9)
at process._tickCallback (node.js:353:17)
[00:37:37] 'unit-test' errored after 20 s
[00:37:37] Error in plugin 'run-sequence(karma)'
Message:
karma callback
npm ERR! Test failed. See above for more details.

**labs.spec.ts:-**

import {
ComponentFixture,
TestComponentBuilder,
} from '@angular/compiler/testing';
import {
beforeEach,
beforeEachProviders,
describe,
expect,
injectAsync,
it,
inject,
fakeAsync,
} from '@angular/core/testing';

import { provide } from '@angular/core';
import { LabsPage } from './labs';
import { Utils } from '../../services/utils';
import {
Config,
Form,
App,
NavController,
NavParams,
Platform,
} from 'ionic-angular';

import {
Http,
BaseRequestOptions,
RequestMethod,
} from '@angular/http';

import { MockBackend, MockConnection } from '@angular/http/testing';
import { LabsProvider } from '../../providers/labs-provider/labs-provider.ts';

class MockClass {
public get(): any {
return '';
}
}

let labsPage: LabsPage = null;
let labsPageFixture: ComponentFixture = null;
let nativeElement: any = null;
let list: any = null;
let mockHttpProvider: any;
mockHttpProvider = {
deps: [ MockBackend, BaseRequestOptions ],
useFactory: (backend: MockBackend, defaultOptions: BaseRequestOptions) : Http => {
return new Http(backend, defaultOptions);
},
};

describe('LabsPage', () => {
beforeEachProviders(() => {
return [
LabsProvider,
MockBackend,
BaseRequestOptions,
provide(Http, mockHttpProvider),
Form,
provide(NavController, {useClass: MockClass}),
provide(NavParams, {useClass: MockClass}),
provide(Config, {useClass: MockClass}),
provide(App, {useClass: MockClass}),
provide(Platform, {useClass: MockClass}),
];
});

beforeEach(injectAsync([TestComponentBuilder], (tcb: TestComponentBuilder) => {
return tcb
.createAsync(LabsPage)
.then((componentFixture: ComponentFixture) => {
labsPageFixture = componentFixture;
labsPage = componentFixture.componentInstance;
labsPageFixture.detectChanges();
nativeElement = labsPageFixture.nativeElement;
list = nativeElement.querySelectorAll('ion-list');
})
.catch(Utils.promiseCatchHandler);
}));

it('initialises', () => {
expect(labsPage).not.toBeNull();
expect(labsPageFixture).not.toBeNull();
});
it('should get a list of labs', () => {
expect(list).not.toBeNull();
});

it('should use an HTTP call to obtain a lab data', inject([LabsProvider, MockBackend], fakeAsync((provider: LabsProvider, backend: MockBackend) => {
backend.connections.subscribe((connection: MockConnection) => {
expect(connection.request.method).toBe(RequestMethod.Get);
expect(connection.request.url).toBe(
'https://abc.xxx.aa/v1/yxys/byDist?lat=20.6734434&lng=-103.3747635');
});
// provider.getLabList(20.6734434, -103.3747635);
})));

});

```
Please help me on this..

**Comment by lathonez** [comment]
Not seen this before.

Could you give me a repo to clone down so I can try it myself?

**Comment by srishiva89** [comment]
This is clone url:-
https://github.com/srishiva89/dx2.git

Replace below files:-
**labs.ts**

import { OnInit, Component }    from '@angular/core';
import { NavController }        from 'ionic-angular';
import { LabsProvider }         from '../../providers/labs-provider/labs-provider.ts';
import {Http, HTTP_PROVIDERS} from '@angular/http';
import {Geolocation} from 'ionic-native';

@Component({
  templateUrl: 'build/pages/labs/labs.html',
  providers: [LabsProvider],
  viewProviders: [HTTP_PROVIDERS],
})
export class LabsPage implements OnInit {

  private title: string;
  private nav: NavController;
  private labsProvider: LabsProvider;
  private labs: any = null;
  private latitude: number;
  private longitude: number;

  constructor(http: Http, nav: NavController, labsProvider: LabsProvider) {
    this.nav = nav;
    this.title = 'Labs';
    this.labsProvider = labsProvider;
  }

  public ngOnInit(): any {
        this.getLocation().then(position => {
        this.latitude = position.coords.latitude;
        this.longitude = position.coords.longitude;
     }).then(val => {
        this.labsProvider.getLabList(this.latitude, this.longitude)
       .subscribe(data => {
        this.labs = data.data.labs;
        });
      });
  }

// get current location
  private getLocation(): any {
    return Geolocation.getCurrentPosition();
  }
}

**labs.spec.ts**
import {
  ComponentFixture,
  TestComponentBuilder,
}                         from '@angular/compiler/testing';
import {
  beforeEach,
  beforeEachProviders,
  describe,
  expect,
  injectAsync,
  it,
  inject,
  fakeAsync,
}                         from '@angular/core/testing';

import { provide }        from '@angular/core';
import { LabsPage }       from './labs';
import { Utils }          from '../../services/utils';
import {
  Config,
  Form,
  App,
  NavController,
  NavParams,
  Platform,
}                         from 'ionic-angular';

import {
  Http,
  BaseRequestOptions,
  RequestMethod,
} from '@angular/http';

import { MockBackend, MockConnection } from '@angular/http/testing';
import { LabsProvider }         from '../../providers/labs-provider/labs-provider.ts';

class MockClass {
  public get(): any {
    return '';
  }
}

let labsPage: LabsPage = null;
let labsPageFixture: ComponentFixture<any> = null;
let nativeElement: any = null;
let list: any = null;
let mockHttpProvider: any;
 mockHttpProvider = {
  deps: [ MockBackend, BaseRequestOptions ],
  useFactory: (backend: MockBackend, defaultOptions: BaseRequestOptions) : Http => {
    return new Http(backend, defaultOptions);
  },
};

describe('LabsPage', () => {
  beforeEachProviders(() => {
    return [
      LabsProvider,
      MockBackend,
      BaseRequestOptions,
      provide(Http, mockHttpProvider),
      Form,
      provide(NavController, {useClass: MockClass}),
      provide(NavParams, {useClass: MockClass}),
      provide(Config, {useClass: MockClass}),
      provide(App, {useClass: MockClass}),
      provide(Platform, {useClass: MockClass}),
    ];
  });

  beforeEach(injectAsync([TestComponentBuilder], (tcb: TestComponentBuilder) => {
    return tcb
      .createAsync(LabsPage)
      .then((componentFixture: ComponentFixture<any>) => {
        labsPageFixture = componentFixture;
        labsPage = componentFixture.componentInstance;
        labsPageFixture.detectChanges();
        nativeElement = labsPageFixture.nativeElement;
        list = nativeElement.querySelectorAll('ion-list');
      })
      .catch(Utils.promiseCatchHandler);
  }));

  it('initialises', () => {
    expect(labsPage).not.toBeNull();
    expect(labsPageFixture).not.toBeNull();
  });
  it('should get a list of labs', () => {
    expect(list).not.toBeNull();
  });

  it('should use an HTTP call to obtain a lab data', inject([LabsProvider, MockBackend], fakeAsync((provider: LabsProvider, backend: MockBackend) => {
          backend.connections.subscribe((connection: MockConnection) => {
          expect(connection.request.method).toBe(RequestMethod.Get);
          expect(connection.request.url).toBe(
            'https://dev.diagnox.me/v2/labs/byDist?lat=20.6734434&lng=-103.3747635');
        });
          // provider.getLabList(20.6734434, -103.3747635);
      })));

});

**labs-provider.ts**
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import 'rxjs/add/operator/map';

@Injectable()
export class LabsProvider {

  private http: Http;
  private static URL: string = 'https://dev.diagnox.me/v2/labs/byDist?lat=';

  constructor(http: Http) {
    this.http = http;
  }

  public getLabList(latitude: number, longitude: number): any {
   return this.http.get(LabsProvider.URL + latitude + '&lng=' + longitude).map(response => response.json());
  }

}

Please let me know if you need any details.

Also while running in emulator, getting below error:-
Loading: /?restart=398921
ionic $
0     745242   log      Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
1     745547   log      DEVICE READY FIRED AFTER, 1744, ms
2     751461   group    EXCEPTION: Error: Uncaught (in promise): [object PositionError]
3     751469   error    EXCEPTION: Error: Uncaught (in promise): [object PositionError]
4     751477   error    STACKTRACE:
5     751482   error    Error: Uncaught (in promise): [object PositionError]
    at resolvePromise (http://192.168.182.99:8100/build/js/zone.js:538:32)
    at resolvePromise (http://192.168.182.99:8100/build/js/zone.js:523:18)
    at http://192.168.182.99:8100/build/js/zone.js:571:18
    at ZoneDelegate.invokeTask (http://192.168.182.99:8100/build/js/zone.js:356:38)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (http://192.168.182.99:8100/build/js/app.bundle.js:35205:41)
    at ZoneDelegate.invokeTask (http://192.168.182.99:8100/build/js/zone.js:355:43)
    at Zone.runTask (http://192.168.182.99:8100/build/js/zone.js:256:48)
    at drainMicroTaskQueue (http://192.168.182.99:8100/build/js/zone.js:474:36)
    at g (http://192.168.182.99:8100/build/js/es6-shim.min.js:11:1946)
    at http://192.168.182.99:8100/build/js/es6-shim.min.js:11:1876
6     751495   groupEnd
7     751504   error    Unhandled Promise rejection:, [object Object], ; Zone:, angular, ; Task:, Promise.then, ; Value:, [object Object]

**Comment by lathonez** [comment]
Not easy to copy and paste code like that when all the formatting has gone.

Why not make a branch for it if you don't want to commit it? Let me know the branch name and I can clone from that.

**Comment by srishiva89** [comment]
only few lines you have to change. Below i bold the changes:-

**labs-provider.ts:-**
private static URL: string = '**https://dev.diagnox.me/v2/labs/byDist?lat=**';

public getLabList(latitude: number, longitude: number): any {
return this.http.get**(LabsProvider.URL + latitude + '&lng=' + longitude**).map(response => response.json());
}

**labs.spec.ts**

expect(connection.request.url).toBe(
'**https://dev.diagnox.me/v2/labs/byDist?lat=20.6734434&lng=-103.3747635**');

 **provider.getLabList(20.6734434, -103.3747635);**

**labs.ts**

Added below line:
**import {Geolocation} from 'ionic-native';**

public ngOnInit(): any {
**this.getLocation().then(position => {
this.latitude = position.coords.latitude;
this.longitude = position.coords.longitude;
}).then(val => {
this.labsProvider.getLabList(this.latitude, this.longitude)**
.subscribe(data => {
this.labs = data.data.labs;
});
});
}

// get current location
**private getLocation(): any {
return Geolocation.getCurrentPosition();
}**

**Comment by lathonez** [comment]
I've tried patching the changes you've highlighted by hand and can't
replicate the issue.

Please create a branch that replicates the issue for you that I can pull
down.

This removes any ambiguity and saves all this back and forth. Also if
others want to contribute to this issue they are easily able and everyone
is on the same page.

**Comment by srishiva89** [comment]
Hi. I pushed the updated changes in github. Now try it. Branch name is **dev_shiva**.
https://github.com/srishiva89/dx2.git

**Comment by srishiva89** [comment]
I facing two issues:-

1) Able to run the app in browser. But it is not running in android emulator. (not displayed list of labs details. Launch app -> select "labs" from side menu)

2) when running unit test, getting **promise uncaught** error.

**Comment by lathonez** [comment]
@srishiva89 much appreciated i will have a look this evening.

**Comment by srishiva89** [comment]
sure lathonez. Thanks for your great help..

**Comment by lathonez** [comment]
Seems to be a private repo.

**Comment by srishiva89** [comment]
then how can i share you?

**Comment by lathonez** [comment]
@srishiva89 I can't support private repositories in my own time as part of this project.

If you need your work to remain private I can provide consultancy to your organisation separately. Contact me by email to discuss.

If you don't need your work to remain private, make it public..

Further reading:

* http://programmers.stackexchange.com/questions/92224/public-vs-private-repositories
* https://help.github.com/articles/making-a-private-repository-public/

**Comment by lathonez** [comment]
@srishiva89 if you managed to resolve this yourself could you let us know how so it could assist future users?

If not please reopen sharing the codebase.

Thanks

**Comment by lathonez** [comment]
For some reason it seems #120 was opened instead of just responding on here.
