### ISSUE TITLE
Cannot find name 'firebase'

### ISSUE THREAD

**Issue by yokeshvaradhan** [lathonez/clicker#117]
I followed your blog for e2e it worked fine. I integrated firebase with my ionic 2 it worked well when i try to i test my my app and i installed all the dependency in your blog i get this err

TypeScript error: /Users/yokesh/3ssdmobile/app/pages/order/view.ts(89,39): Error TS2304: Cannot find name 'firebase'.
TypeScript error: app/app.ts(33,9): Error TS2304: Cannot find name 'firebase'.
TypeScript error: typings/globals/firebase/index.d.ts(323,2): Error TS2300: Duplicate identifier 'export='.
TypeScript error: typings/modules/firebase/index.d.ts(509,1): Error TS2300: Duplicate identifier 'export='.

but i have firebase@3.0.5  es6-promise

system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.3
Xcode version: Xcode 7.3.1 Build version 7D1014 

any idea to fix this issue
i even followed this link https://forum.ionicframework.com/t/cannot-find-name-firebase/46839/5

**Comment by lathonez** [comment]
You need to install typings for firebase.

`typings install dt~firebase --global --save`

Refernence: https://github.com/angular/angularfire2/issues/182

**Comment by lathonez** [comment]
#191
