### ISSUE TITLE
Debug original function invoked by spec

### ISSUE THREAD

**Issue by masimakopoulos** [lathonez/clicker#119]
Hi,

not sure if this has been answered before, but couldn't find anything related. 
I am trying to debug why a test fails and although using `npm run karma` and opening a second tab with debug as per instructions gives me the ability to add break points to the spec code, the code to be tests is minified and I cannot place a break point there. Debugging the actual test code is only half the story. Am I missing something?

<img width="1282" alt="screenshot 2016-07-11 16 21 42" src="https://cloud.githubusercontent.com/assets/803983/16732000/a7d6ed36-4783-11e6-8e99-f4179cc747d1.png">

I also clicked on the notification about pretty printing the minified file, which made no difference

**Comment by lathonez** [comment]
No, you're right. Apparently I've not had to dig this far before. It's exactly as you say.

The (source) source map works with `npm start` so hopefully we're just missing some config.

**Comment by lathonez** [comment]
It's the transform that breaks it for some reason, these lines here:

https://github.com/lathonez/clicker/blob/master/test/karma.config.js#L39-L44

My plan is to:

* remove transform from karma-debug as we're not using the coverage there anyway, thereby solving your issue
* remove source maps from npm test (straight karma run) to give quicker tests

**Comment by lathonez** [comment]
I didn't end up removing the sourcemaps from `npm test` in the end. I didn't notice much difference in transpile time and they do give (more) useful traces when things go wrong.

Removing the transform from debug mode has solved the issue for me:

![screenshot-20160712102810-1118x618](https://cloud.githubusercontent.com/assets/7236936/16751334/f9b90be6-481b-11e6-8cfd-d23b13916b4c.png)

**Comment by masimakopoulos** [comment]
Awesome, just tried it and it works great. Thanks for the quick resolution.
