### ISSUE TITLE
Import path in gulpfile.ts > cannot find module path

### ISSUE THREAD

**Issue by ebors** [lathonez/clicker#123]
Hi, 

my editor is showing, that cannot find the module path.
import { join } from 'path';

what is a difference between this and var path         = require('path'); ?

Thanx for help,

**Comment by lathonez** [comment]
Hey,

Path is standard node, the typings come from this line in [typings.json](https://github.com/lathonez/clicker/blob/master/typings.json#L8).

If you have your editor set up correctly (I use ST3, which looks at [tsconfig.json](https://github.com/lathonez/clicker/blob/master/tsconfig.json#L9) to find the typings iirc), it should be aware of the module path if you have the typings installed.

> what is a difference between this and var path = require('path'); ?

We're using [`ts-node`](https://github.com/TypeStrong/ts-node) to get the benefits of typescript in our gulpfile. If you don't want to use it you can write your gulpfile in straight javascript (like [Ionic's](https://github.com/lathonez/clicker/blob/master/gulpfile.js)).

My problem is that now I've got used to Typescript I find myself making mistakes more often when not using it. Using the ES6 Import Syntax + typescript allows me to think less about syntax / libraries / variable names, and concentrate on what my code is actually doing.

e.g.

```javascript

// this fails in the typescript compiler (and warns in the editor):
import { notExsit } from 'path';

// this shows no warnings but fails at runtime
var notExist = require('path').notExist;
```

and

```javascript
import { join } from 'path';

// this fails in the typescript compiler (and warns in the editor):
join.nonExistingMethod('foo');

var join = require('path').join;

// this shows no warnings but fails at runtime
join.notExistingMethod('foo');
```

Please reopen if you have further questions.
