### ISSUE TITLE
Breaking changes Beta 11 - push method

### ISSUE THREAD

**Issue by dgroh** [lathonez/clicker#127]
I posted this issue on Ionic forum:

https://forum.ionicframework.com/t/beta-11-jasmine-error-after-upgrade-to-beta-11/59976

The mock for the push method is not working after upgrading to Beta 11

**Comment by lathonez** [comment]
It does exist, this is from nav.d.ts in `node_modules/ionic-angular/components/nav/nav-controller.d.ts`

```javascript
    /**
     * Push a new component onto the current navication stack. Pass any aditional information
     * along as an object. This additional information is acessible through NavParams
     *
     * @param {Page} page  The page component class you want to push on to the navigation stack
     * @param {object} [params={}] Any nav-params you want to pass along to the next view
     * @param {object} [opts={}] Nav options to go with this transition.
     * @returns {Promise} Returns a promise which is resolved when the transition has completed.
     */
    abstract push(page: any, params?: any, opts?: NavOptions, done?: Function): Promise<any>;
```

Why do you reference the prototype directly as opposed to [mocking out the class](https://github.com/lathonez/clicker/blob/master/test/mocks.ts#L19-L44)?

**Comment by dgroh** [comment]
I saw a sample in the internet, as I only need the push method I don't see any reason to create a mock class and it was working with beta 10, that is why I'm wondering.

**Comment by dgroh** [comment]
Why is it trying to get it from `node_modules/jasmine-core/lib/jasmine-core/jasmine.js` ?

**Comment by lathonez** [comment]
Because it's running in Jasmine I guess.

The point of mocking is to not use the code we're mocking out. By referencing the prototype directly your tests are dependent on the underlying NavController.

e.g. you aren't mocking at all, you may as well pass the NavController class through directly.

**Comment by dgroh** [comment]
You are right, so I'm closing the bug
