### ISSUE TITLE
SntaxError: Unexpected token import

### ISSUE THREAD

**Issue by rtm** [lathonez/clicker#138]
Although my project is set up as close to yours as I can, when running gulpfile.ts I get

    (function (exports, require, module, __filename, __dirname) { import { join } from 'path';
    SyntaxError: Unexpected token import

Obviously this file is not getting transpiled property. Where and how is that supposed to be happening?

**Comment by lathonez** [comment]
Hi Bob,

What command are you running to produce this error?

Could you confirm that cloning and testing our project works for you?

Transpilation of gulpfile.ts is done by ts-node (
https://github.com/TypeStrong/ts-node).

The unit testing blog post (
http://lathonez.github.io/2016/ionic-2-unit-testing/) runs through the
minimal steps needed to apply our unit testing methodology to an ionic
project. Have you followed it?

Thanks

**Comment by lathonez** [comment]
Hi Non,

Let me know if you managed to resolve this so it might help others with the same issue.

If you didn't manage to resolve, reopen and reply to the above.

Thanks,

Stephen
