### ISSUE TITLE
Build failing due to 143

### ISSUE THREAD

**Issue by lathonez** [lathonez/clicker#144]
https://travis-ci.org/lathonez/clicker/builds/158345791

Presumably this is the error that @pvdyck was referring to:

```
✔ 40 tests completed
✖ 2 tests failed
FAILED TESTS:
  ClickerForm
    ✖ passes new clicker through to service
      Chrome 53.0.2785 (Linux 0.0.0)
    Expected spy newClickerLocal to have been called with [ Object({ clickerNameInput: 'dave' }) ] but it was never called.
        at Object.<anonymous> (/tmp/app/components/clickerForm/clickerForm.spec.ts:37:42 <- /tmp/234559cf23adb7a1c4581247f438d92e.browserify:159:58)
    Expected spy resetControl to have been called with [ FormControl({ validator: Function, asyncValidator: null, _pristine: false, _touched: false, _onChange: [ Function ], _value: 'dave', _errors: null, _status: 'VALID', _valueChanges: EventEmitter({ _isScalar: false, destination: undefined, source: undefined, observers: [  ], isUnsubscribed: false, isStopped: false, hasErrored: false, dispatching: false, hasCompleted: false, __isAsync: false }), _statusChanges: EventEmitter({ _isScalar: false, destination: undefined, source: undefined, observers: [  ], isUnsubscribed: false, isStopped: false, hasErrored: false, dispatching: false, hasCompleted: false, __isAsync: false }), _parent: FormGroup({ validator: null, asyncValidator: null, _pristine: false, _touched: false, controls: Object({ clickerNameInput: <circular reference: Object> }), _optionals: Object({  }), _valueChanges: EventEmitter({ _isScalar: false, destination: undefined, source: undefined, observers: [  ], isUnsubscribed: false, isStopped: false, hasErrored: false, dispatching: false, hasCompleted: false, __isAsync: false }), _statusChanges: EventEmitter({ _isScalar: false, destination: undefined, source: undefined, observers: [  ], isUnsubscribed: false, isStopped: false, hasErrored: false, dispatching: false, hasCompleted: false, __isAsync: false }), _value: Object({ clickerNameInput: 'dave' }), _errors: null, _status: 'VALID' }) }) ] but it was never called.
        at Object.<anonymous> (/tmp/app/components/clickerForm/clickerForm.spec.ts:38:31 <- /tmp/234559cf23adb7a1c4581247f438d92e.browserify:160:57)
```

[Confirmed](https://travis-ci.org/lathonez/clicker/builds/158280728)

No idea how we get from there ^ to the [needed fix](https://github.com/lathonez/clicker/pull/143/commits/185390e3b5a717e3fbebd478b8826bcb39d94ae8)

This is what I get for not paying better attention to the travis builds in PRs.

**Comment by lathonez** [comment]
Can't replicate down here.

**Comment by lathonez** [comment]
https://travis-ci.org/lathonez/clicker/builds/158281180

So what the [needed fix](https://github.com/lathonez/clicker/pull/143/commits/185390e3b5a717e3fbebd478b8826bcb39d94ae8) did was to bypass the failing tests by causing karma to exit with a zero status.

We can see from the above test during the PR that the tests were actually still failing.

At least that all makes sense now.

**Comment by lathonez** [comment]
caused by #143

**Comment by lathonez** [comment]
Until I can replicate down here it's going to be very hard to debug why these have started failing.

Have tried:

* node version
* phantom, chrome, phantom + chrome

For now I'll comment out the failing tests so they don't impact anyone else.

**Comment by lathonez** [comment]
77b1d13

**Comment by pvdyck** [comment]
It is not the same behavior. It is another problem. I don't have it on my side and on my CI either.

**Comment by lathonez** [comment]
>  It is another problem. 

Nope. We can see this from your PR's CI builds:

* First build fails with the exact same issue: https://travis-ci.org/lathonez/clicker/builds/158280728
* Second build passes as you made the change to ignore the exit code. We can see from the build logs that the exact same issue is encountered: https://travis-ci.org/lathonez/clicker/builds/158281180

As I said I should have paid more attention to these failed builds when you weren't able to explain why that change was needed.

I've no idea why the tests are now failing. I guess some behaviour has changed in one of the upgrades.

**Comment by pvdyck** [comment]
What I meant is that the change in the gulp file had a different origin when I encountered it. PhantomJS - the karma server - was not launching at all without the change in the gulp task.
Now some tests are passing -- BTW I can't reproduce and it's working in gitlab-ci -> do you have an npm cache with travis-ci ?

**Comment by lathonez** [comment]
no longer an issue
