### ISSUE TITLE
Loading all components in index.ts

### ISSUE THREAD

**Issue by codestellar** [lathonez/clicker#147]
Hi Lathonez,

I find that you are exporting everything in index.ts for example for components/services/models and then while importing all we need is import { componentName } from ../models_or_services_compoennt. This looks cleaner undoubtedly but I am not sure that it will now load only this component because the dependency graph generated will link to all the components listed in index.ts and hence this is an overhead.

Can you please help me understanding this?

**Comment by lathonez** [comment]
If you mean barrels, see

#109 and http://tattoocoder.com/angular2-barrels/

If you don't mean barrels, please explain what you mean (and reopen)

**Comment by codestellar** [comment]
Great Thanks @lathonez
