### ISSUE TITLE
Error when incorporating

### ISSUE THREAD

**Issue by soupman99** [lathonez/clicker#154]
Followed the tutorial a couple times with no luck.  Ended up cloning the repo & placing my own code in the src folder.  Now I'm getting this error and have no idea what to do to fix it.

`  Error: Error in ./MyApp class MyApp - inline template:0:0 caused by: No provider for GestureController!                
    Error: No provider for GestureController!    `

Any advise?

**Comment by lathonez** [comment]
Compare the line where I create an instance of `ClickerApp` (https://github.com/lathonez/clicker/blob/master/src/app/app.spec.ts#L10) to where you create an instace of `MyApp`.

The error you're getting `No provider for ... ` means that the TestBed doesn't have a provider for whatever it's telling you (`GeustureController`).

You can add providers to the array here: https://github.com/lathonez/clicker/blob/master/src/test.ts#L49-L58

When I tried to do this for the app component (`MyApp`) in your case, it ended up being a rabbit hole of providers until it ended up with something I couldn't find, hence I don't use `TestBed.createComponent` on my main app component.

**Comment by soupman99** [comment]
Ohhhh.  Gotcha yeah.  Testing the stuff other than the main
