### ISSUE TITLE
Try to implement angular2-redux fails

### ISSUE THREAD

**Issue by lujakob** [lathonez/clicker#156]
Hi. 
First of all thanks for this very helpful repo. 
I am trying to setup the karma testrunner based upon your implementation for my ionic redux app. When I try to create the store in test.ts I get the following error running the test:

Uncaught ReferenceError: process is not defined
  at webpack:///Users/luki/Applications/ionic/ionic2-redux-example/~/redux/es/index.js:14:0 <- src/test.ts:65041

You can see my implementation in https://github.com/lujakob/ionic2-redux-example/blob/master/src/test.ts
(The app runs and a basic test runs as well, when 
`exportconst appStoreFactory` 
in line 37 and 
`providers: [
          {
              provide: AppStore,
              useValue: appStoreFactory
          }
      ],`
in line 68 is outcommented.

Any help is much appreciated, as I am probably missing fundamental knowledge about how test runners work, to be able to make correct configurations.

**Comment by lathonez** [comment]
Sorry that I'm only just getting around to this. I've been flat out with work this week. I'm hoping to improve things a lot of the coming week.

I'm looking into this now.

Thanks,

**Comment by lathonez** [comment]
Replicated

**Comment by lathonez** [comment]
https://github.com/rollup/rollup/issues/487

**Comment by lathonez** [comment]
https://github.com/angular-redux/ng2-redux/issues/213

**Comment by lathonez** [comment]
Fixed here: in latest version of CLI: https://github.com/angular/angular-cli/commit/e23e0fe

**Comment by lathonez** [comment]
@lujakob - upgrade ng-cli to beta.18 to solve this (as above).

A bit of background re the testing - we're 100% aligned with ng-cli. This is great because we can use their fantastic community for support (as you see above).

Thus, for anything testing related you can search for how it would be done using ng-cli to guide your implementation.

**Comment by lujakob** [comment]
Thanks so much for your help. Updating the angular-cli didn't fix the issue, but you brought me to the right direction. Setting the process.env.NODE_ENV in test.js as a workaround though did. I added the following in the first line of test.ts
`(<any>window).process = { env: { NODE_ENV: 'development' }};`
