### ISSUE TITLE
Jasmine functions not recognised in test

### ISSUE THREAD

**Issue by nieldw** [lathonez/clicker#157]
I followed the steps in the blog post to set up unit tests, however when I try to run "your first unit test", fitted to one of my pages, the Jasmine functions are not recognised.

When running I first see:

    ERROR in ./src/test.ts
    Module not found: Error: Can't resolve './services/clickers.mock'

Output related to my test:

    Cannot find name 'describe'.
    Cannot find name 'beforeEach'.
    Cannot find name 'it'.
    Cannot find name 'expect'.

And this, from my page ts file:

    Cannot find name 'require'.

What could be the possible causes? I've checked that the dev dependencies are install in my node_modules.

---
```
$ ionic info

Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v6.6.0```

**Comment by derksacklowski** [comment]
Hi,

try including 

`    
"compilerOptions": {
    "types": [
        "jasmine"
    ]
}`

in your tsconfig.json

Maybe you also have to add 

`"@types/jasmine": "latest",`

to your package.json

**Comment by nieldw** [comment]
@derksacklowski you are right!

Also, I had to remove the references to `clickers.mock` in `src/test.ts` and replace them with my own mocks.
