### ISSUE TITLE
npm test hangs

### ISSUE THREAD

**Issue by m5rk** [lathonez/clicker#161]
I followed the instructions here:

http://lathonez.github.io/2016/ionic-2-unit-testing/

When I run `npm test`, it produces this output and then hangs:

```
npm test

> ionic-hello-world@ test /Users/markmceahern/Repo/manifestly/manifestly-ionic
> ng test

31 10 2016 11:15:59.100:WARN [karma]: No captured browser, open http://localhost:9876/
31 10 2016 11:15:59.116:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
31 10 2016 11:15:59.117:INFO [launcher]: Launching browser Chrome with unlimited concurrency
31 10 2016 11:15:59.125:INFO [launcher]: Starting browser Chrome
31 10 2016 11:16:01.310:INFO [Chrome 54.0.2840 (Mac OS X 10.12.0)]: Connected on socket /#LUO0sesivqxAR2ptAAAA with id 36653737

START:

Finished in 0.003 secs / 0 secs

SUMMARY:
✔ 0 tests completed
```

**Comment by m5rk** [comment]
Ah, found it:

https://github.com/lathonez/clicker/blob/master/karma.conf.js#L39

```
    singleRun: false
```

When change that to `true`, it runs the suite and exits as expected.

**Comment by lathonez** [comment]
Yeah, singleRun: false is the default behaviour in ng-cli so I'm leaving it at that.

For CI you can set it to true via the cli:

https://github.com/lathonez/clicker/blob/master/.travis.yml#L43

**Comment by masimakopoulos** [comment]
or you could add a conditional in karma.config.js depending on environmental variable set by your CI
```
module.exports = function (config) {
    ........
    singleRun: false
  });

  if (process.env.TEAMCITY) {
    config.browsers = ['PhantomJS'];
    config.reporters = ['teamcity'];
    config.singleRun = true;
  }
};
```
I find it reduces CI maintenance if something changes in how tests are run.
