### ISSUE TITLE
Blog about Travis config?

### ISSUE THREAD

**Issue by morphatic** [lathonez/clicker#162]
Thank you for sharing your testing config! It's perfect for my current project. 

I've tried to figure out your Travis setup, but I'm getting stuck on some of the directories that are specific to your project (e.g. `/home/travis/build/lathonez/clicker/`) and figuring out what values I should change these to in my own project.

Thanks!

**Comment by lathonez** [comment]
It's been on my list to do for ages, you're the first one that's asked for it.

It was tricky enough to get going, particularly the android build. The goal for me eventually is to get a matrix building iOS also.

IIRC I couldn't get `~/` to expand properly, so I just had to use the absolute path (with my travis username). If you use the same config just change `lathonez` to your username.

If you've other questions I'm happy to help, it's unlikely that I'll have time to blog on it in the near future.

**Comment by lathonez** [comment]
> It looks like $TRAVIS_BUILD_DIR resolves to /home/travis/build/[username]/[projectname] and is a pre-configured environment variable.

Nice: 9f81dc4

> Perhaps it was because the failures happened in other parts of the code.

Yes those log files will be populated only if the server manages to run

>  Still working out how to get the e2e stuff working

I had a look at that build, you're missing `ts-node` 

> but your examples have been EXCELLENT and I'm confident I'll figure it out. Much gratitude!

Thanks - and thanks for the change here.

**Comment by morphatic** [comment]
[Success!!!](https://travis-ci.org/morphatic/Scoop/builds/172954440)
