### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by shinta5150** [lathonez/clicker#165]
In my ts file i have the following import:
import _ from 'lodash';

However when I run a test that uses lodash, it finds that lodash is undefined.
Module '"lodash"' has no default export.

**Comment by shinta5150** [comment]
Found a solution.
Use lodash-es instead of lodash.
Then import using import * as _ from 'lodash-es/lodash';

This fixed it

**Comment by kamok** [comment]
Can you explain more on what you did? I'm having the same problem now. Did you have to include lodash in karma.conf's file array?

**Comment by kamok** [comment]
Nevermind you don't need to import it. For future readers, follow this http://ionicframework.com/docs/v2/resources/third-party-libs/ to import third party libs. Replace lodash with lodash-es and you should be able to use lodash in the tests. Do not need to  include lodash-es in karma.conf's file array?
