### ISSUE TITLE
Ionic2 unit testing npm test is working but ionic serve fails!!

### ISSUE THREAD

**Issue by Asiq** [lathonez/clicker#167]
Here, I have followed all the steps from this [](http://lathonez.github.io/2016/ionic-2-unit-testing/)   and used the same in my project also. But npm test is running successfull, but fails with ionic serve.

ionic serve it throws error with "cannot find name 'describe,beforeEach,it and expect'".
Could you please help me out on this.
If you need more details also let me know.

**Comment by tja4472** [comment]
Add the following to tsconfig.json, https://github.com/lathonez/clicker/blob/master/tsconfig.json#L19
```
  "exclude": [
    "node_modules",
    "e2e",
    "**/*.spec.ts"
  ],
```


See also #159

**Comment by Asiq** [comment]
Yes now it is working fine..Thanks @tja4472
