### ISSUE TITLE
Warning issues when i run the npm test in ionic2 unit testing

### ISSUE THREAD

**Issue by Asiq** [lathonez/clicker#168]
Hey, I am facing some warning issues when i run the npm test in ionic2  unit testing. Need to fix those issues. Could you please help me out on this.

Here list of some warning issues..

WARNING in ./~/ionic-angular/components/loading/loading-transitions.js
Cannot find source file 'loading-transitions.ts': Error: Can't resolve './loading-transitions.ts'

WARNING in ./~/ionic-angular/components/modal/modal-transitions.js
Cannot find source file 'modal-transitions.ts': Error: Can't resolve './modal-transitions.ts'

WARNING in ./~/ionic-angular/components/popover/popover-transitions.js
Cannot find source file 'popover-transitions.ts': Error: Can't resolve './popover-transitions.ts'

WARNING in ./~/ionic-angular/components/picker/picker-transitions.js
Cannot find source file 'picker-transitions.ts': Error: Can't resolve './picker-transitions.ts'

WARNING in ./~/ionic-angular/components/toast/toast-transitions.js
Cannot find source file 'toast-transitions.ts': Error: Can't resolve './toast-transitions.ts'

**Comment by lathonez** [comment]
See https://github.com/lathonez/clicker/issues/148#issuecomment-254436635

https://github.com/lathonez/clicker/issues/158

**Comment by Asiq** [comment]
Hey, Actually i am not understand the comments which gave in #148  and #158 .As well here in Ionic2 folder structure doesn't have webpack.common.js file. How do i update the webpack file.Could you please guide me.

**Comment by lathonez** [comment]
Presently I don't believe it's possible. ng-cli need to allow webpack module extensions (which is on their roadmap).

In case it isn't obvious from the comments, the issue is upstream with those modules not providing correct mapping, anything you do to fix it is working around issues with those modules.

That is my understanding anyway

**Comment by kamok** [comment]
@lathonez Thanks for the response. I thought it was a problem on my end because when I cloned the original clicker, it didn't give me the Warnings. While after a few weeks since I built my Ionic 2 project on top of it, it started giving me Warnings.
