### ISSUE TITLE
unit testing, why callThrough is used?

### ISSUE THREAD

**Issue by muhammedbasilsk** [lathonez/clicker#177]
Hey @lathonez ,

I have a doubt on [a line](https://github.com/lathonez/clicker/blob/master/src/components/clickerForm/clickerForm.spec.ts#L32) you wrote in the spec.

```
spyOn(instance['clickerService'], 'newClicker').and.callThrough();
```

Here why should we use **callThrough** (which will trigger the actual service instead of the mock.) ? Why the mock service method is not used here?

**Comment by lathonez** [comment]
The mock is provided at compile time:

https://github.com/lathonez/clicker/blob/master/src/components/clickerForm/clickerForm.spec.ts#L11

and 

https://github.com/lathonez/clicker/blob/master/src/test.ts#L63.

So no the actual service isn't in use at all.

**Comment by muhammedbasilsk** [comment]
Thanks for the explanation. Really appreciate it. 👍

**Comment by lathonez** [comment]
#191
