### ISSUE TITLE
Getting 0 tests completed after running clicker

### ISSUE THREAD

**Issue by ronaksbhavsar** [lathonez/clicker#178]
![blob](https://cloud.githubusercontent.com/assets/5341652/20517073/83e2245e-b0bf-11e6-8af7-dd046a996b73.png)

**Comment by lathonez** [comment]
Please confirm you have performed the following steps:

```
git clone git@github.com:lathonez/clicker.git
cd clicker
npm install
npm test
```

**Comment by ronaksbhavsar** [comment]
yes
i have followed above steps

**Comment by ronaksbhavsar** [comment]
still same

**Comment by lathonez** [comment]
paste the output of the following:

`node --version`

`npm list -g --depth=0`

**Comment by ronaksbhavsar** [comment]
![image](https://cloud.githubusercontent.com/assets/5341652/20517419/f74b97da-b0c0-11e6-8904-648466724724.png)

**Comment by ronaksbhavsar** [comment]
please check above screenshot

**Comment by lathonez** [comment]
Should be fine I think.

Does `npm start` work ok?

**Comment by ronaksbhavsar** [comment]
yes it working fine when i run npm start , I am also new to karma and jasmine for ionic 2 .

**Comment by ronaksbhavsar** [comment]
@lathonez Hi, please update me if you have found anything

**Comment by lathonez** [comment]
Nothing concrete, sorry.

Try:
* upgrading node to latest LTS (should be 6.5.0)
* typescript to 2.0.7

After you've done that:

`npm cache clean`

and these steps again.

If you want to try to debug it yourself, you need to figure out why no specs are being found.

This line here: https://github.com/lathonez/clicker/blob/master/src/test.ts#L36 is a good starting point

**Comment by ronaksbhavsar** [comment]
ok

**Comment by lathonez** [comment]
BEFORE you do that, can you paste the entire output of `npm test`.

Please copy and paste (no screenshot).

**Comment by ronaksbhavsar** [comment]
ok

**Comment by ronaksbhavsar** [comment]
I have updated node to 6.5.0 , Typescript is already 2.0.7 and installed node modules again. still same

**Comment by ronaksbhavsar** [comment]
before Upgrading Node

> Clicker@2.3.0 test E:\
> ng test --code-coverage

22 11 2016 14:51:02.051:WARN [karma]: No captured browser, open http://localhost:9876/
22 11 2016 14:51:02.051:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
22 11 2016 14:51:02.051:INFO [launcher]: Launching browser Chrome with unlimited concurrency
22 11 2016 14:51:02.309:INFO [launcher]: Starting browser Chrome
22 11 2016 14:51:05.749:INFO [Chrome 56.0.2922 (Windows 10 0.0.0)]: Connected on socket /#lyKl8I9gcQo-HU7zAAAA with id 4991
5639

START:

Finished in 0.002 secs / 0 secs

SUMMARY:
√ 0 tests completed

**Comment by lathonez** [comment]
Apply this diff for debug:

```diff
diff --git a/src/test.ts b/src/test.ts
index d12d17f..ca87bd3 100644
--- a/src/test.ts
+++ b/src/test.ts
@@ -33,7 +33,7 @@ Promise.all([
     );
   })
   // Then we find all the tests.
-  .then(() => require.context('./', true, /\.spec\.ts/))
+  .then(() => require.context('./pages/page2/'))
   // And load the modules.
   .then(context => context.keys().map(context))
   // Finally, start Karma to run the tests.
```

**Comment by ronaksbhavsar** [comment]
ok

**Comment by ronaksbhavsar** [comment]
How to debug tests?

**Comment by lathonez** [comment]
Apply the diff and paste the output of npm test.

**Comment by ronaksbhavsar** [comment]
Still same
E:\clicker>npm test

> Clicker@2.3.0 test E:\clicker
> ng test --code-coverage

22 11 2016 16:43:39.118:WARN [karma]: No captured browser, open http://localhost:9876/
22 11 2016 16:43:39.133:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
22 11 2016 16:43:39.133:INFO [launcher]: Launching browser Chrome with unlimited concurrency
22 11 2016 16:43:39.313:INFO [launcher]: Starting browser Chrome
22 11 2016 16:43:40.938:INFO [Chrome 56.0.2922 (Windows 10 0.0.0)]: Connected on socket /#_Jz5YATKLlf85fM7AAAA with id 3159
998

START:

Finished in 0.002 secs / 0 secs

SUMMARY:
√ 0 tests completed

**Comment by lathonez** [comment]
try using ng-cli directly:

```
npm install -g angular-cli
ng new PROJECT_NAME
cd PROJECT_NAME
ng test
```

**Comment by ronaksbhavsar** [comment]
@lathonez  can you please help me out from this issue?

**Comment by ronaksbhavsar** [comment]
Hi @lathonez , 
**I have created new project by given commands. and logs are given below:**

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

E:\CLI-testProject>ng test
25 11 2016 11:19:36.455:WARN [karma]: No captured browser, open http://localhost:9876/
25 11 2016 11:19:36.465:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
25 11 2016 11:19:36.465:INFO [launcher]: Launching browser Chrome with unlimited concurrency
25 11 2016 11:19:36.465:INFO [launcher]: Starting browser Chrome
25 11 2016 11:19:42.818:INFO [Chrome 56.0.2922 (Windows 10 0.0.0)]: Connected on socket /#5G04u69L8P0zPFMUAAAA with id 6892
4662
Chrome 56.0.2922 (Windows 10 0.0.0): Executed 3 of 3 SUCCESS (0.433 secs / 0.423 secs)

**Comment by ronaksbhavsar** [comment]
![image](https://cloud.githubusercontent.com/assets/5341652/20615613/b49683da-b301-11e6-9afb-9a810684ab5e.png)

**Comment by ronaksbhavsar** [comment]
it's working fine in mac. i have tested it

**Comment by ronaksbhavsar** [comment]
it's working fine it was throwing an exception in debugger

**Comment by ronaksbhavsar** [comment]
https://github.com/angular/angular-cli/issues/2125

**Comment by ronaksbhavsar** [comment]
![image](https://cloud.githubusercontent.com/assets/5341652/20623456/af71da04-b32d-11e6-8698-799f745ad7c9.png)

**Comment by ronaksbhavsar** [comment]
thanks for your support

**Comment by lathonez** [comment]
I am away currently away. Will pick this up when I return. Sometime mid
December.

On 25 Nov 2016 19:08, "ronaksbhavsar" <notifications@github.com> wrote:

angular/angular-cli#2125
<https://github.com/angular/angular-cli/issues/2125>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/lathonez/clicker/issues/178#issuecomment-262934135>,
or mute
the thread

**Comment by ronaksbhavsar** [comment]
Hi, It's been Resolved

**Comment by lathonez** [comment]
Can you tell us what you did to resolve it?

**Comment by ronaksbhavsar** [comment]
![image](https://cloud.githubusercontent.com/assets/5341652/20697197/5a90f5fe-b61d-11e6-9f30-fe9aabaf234e.png)
I have added this code for typescript to identify mime type for browser

**Comment by andrewgy8** [comment]
For the lazy in karma.conf.js : ```   
 mime: {
      'text/x-typescript': ['ts', 'tsx']
    }```

**Comment by lathonez** [comment]
@andrewgy8 - should I be adding this to karma.conf.js?

**Comment by andrewgy8** [comment]
I had the same issue as @ronaksbhavsar, and that seemed to do the trick.

**Comment by lathonez** [comment]
5c0ffeb (will push in a bit)

**Comment by ronaksbhavsar** [comment]
yes you should add

**Comment by ronaksbhavsar** [comment]
@lathonez  Why you blocked me into gitter into 'clicker ' room?

**Comment by lathonez** [comment]
I removed the room, no one uses it.

**Comment by ronaksbhavsar** [comment]
@lathonez  ok, can i comment here for issues?

**Comment by ronaksbhavsar** [comment]
@lathonez Actually i want to debug protractor, do you know how to debug through visual studio code?

**Comment by Wolfium** [comment]
I can confirm that the mime type setting in karma already there in my 2 projects, one working and the other don't is not the solution.

I am thinking in something related with the libraries versions from angular saying 4.1.2, working one had 4.1.1 and after upgrade failing, it got 4.1.3 that is working properly.

Unfortunatly from the yarn upgrade I can't reproduce it now, both project have testing working properly.
Anyway, just to notice output ng version from 0 test (having tests inside) run project:
```
@angular/cli: 1.0.1
node: 7.3.0
os: win32 x64
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/core: 4.1.2
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/router: 4.1.2
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.2
```
Hope this helps.

Regards
