### ISSUE TITLE
No provider for GestureController!

### ISSUE THREAD

**Issue by Uriel96** [lathonez/clicker#180]
I followed the steps for unit testing ionic 2 applications you gave in http://lathonez.github.io/2016/ionic-2-unit-testing/ and its giving the following error:
![captura de pantalla 67](https://cloud.githubusercontent.com/assets/6753760/20575304/56cc5cfe-b17e-11e6-899b-748b934a3565.png)

**Comment by lathonez** [comment]
I'm AFK at the moment. Someone else has raised the exact same issue in the
past if you search closed issues you should find it.

**Comment by Uriel96** [comment]
Okay, thank you. In my project I have only one provider called "Service" and I already added it but it is still giving me that error, I only have one test in a 'page' called "Dashboard". I don't know how to fix these error since what I understood from the answer is that you need to add all the providers and I already did.

**Comment by msalcala11** [comment]
@Uriel96 I ran into a similar issue and resolved it by adding `GestureController` as a provider in `test.ts`. You can import `GestureController` from `ionic-angular`.

**Comment by muhammedbasilsk** [comment]
Adding  example for @msalcala11 's answer.
```ts
import { GestureController }  from 'ionic-angular';

...

public static configureIonicTestingModule(components: Array<any>, overrideProviders: Array<any>): typeof TestBed {
    return TestBed.configureTestingModule({
      declarations: [
        ...components,
      ],
      providers: [
        App, Platform, Form, Keyboard, MenuController, NavController, GestureController
        {provide: Config, useClass: ConfigMock}
      ],
      imports: [
        FormsModule,
        IonicModule,
        ReactiveFormsModule,
      ],
    })
  }
```

**Comment by Uriel96** [comment]
Thank you!! That did the work. It was straight forward after all XD
