### ISSUE TITLE
Can't resolve all parameters in TestUtils (not really an issue with clicker)

### ISSUE THREAD

**Issue by masimplo** [lathonez/clicker#182]
Hi @lathonez,

I tried to avoid opening this "issue" as it is not directly related to your setup but I have struggled with this for a couple days now and you might have some helpful input. 
I am using both Karma and wallaby.js to run my tests. All tests run fine on both runners so far, but I haven't written any tests using the TestBed up until now. I have written a simple test for a component like:

```
describe('FirstCommunication::Component', function() {
    beforeEach(async(() => TestUtils.beforeEachCompiler([FirstCommunicationComponent]).then(compiled => {
      fixture = compiled.fixture;
      instance = compiled.instance;
    })));

    afterEach(function() {
      fixture.destroy();
    });

    it('initialises', function() {
      expect(instance).not.toBeNull();
    });
```

FirstCommunicationComponent takes two injectables. A custom service holding the session and ionic's ModalController service. 
```
constructor(private _session: SessionService, private _modal: ModalController) {
```

In karma this tests runs fine, but in wallaby I get a 
>​​Failed: Can't resolve all parameters for FirstCommunicationComponent: (SessionService, ?)
on `TestUtils.beforeEachCompiler` line 

So for some reason ionic services are not registered in the DI or sth.

This is what configureIonicTestingModule looks like:
```
  public static configureIonicTestingModule(components: Array<any>): typeof TestBed {
    return TestBed.configureTestingModule({
      declarations: [
        ...components,
      ],
      providers: [
        App, Platform, Form, Keyboard, MenuController, NavController, Config,
        { provide: ModalController, useClass: PresentableControllerMock },
        { provide: SessionService, useClass: SessionServiceMock },
      ],
      imports: [
        FormsModule,
        IonicModule,
        ReactiveFormsModule,
      ],
    });
  }
```

My wallaby-tests.ts (using it instead of tests.ts that references karma) is identical to tests.ts without these lines:
```
  // Then we find all the tests.
  .then(() => require.context('./', true, /\.spec\.ts/))
  // And load the modules.
  .then(context => context.keys().map(context))
  // Finally, start Karma to run the tests.
  .then(__karma__.start).catch(__karma__.error);
```
mainly because I don't fully understand what they are doing (apart from the last one) and wallaby "worked" without them. I have also extracted TestUtils to their own file.

Any idea on why Ionic providers are special and not recognised by the DI? I am guessing it has to do with the lines I removed from tests.ts, but not sure.

**Comment by ArtemGovorov** [comment]
@masimplo We have seen the issue like this before, and it was related to `*.d.ts` files. Try excluding them as described: https://github.com/wallabyjs/public/issues/839.

**Comment by masimplo** [comment]
@ArtemGovorov I can't believe you answered this here. I haven't even linked back to wallaby repo. I am amazed. 
Ignoring d.ts files did the trick. I had searched through wallaby repo issues but didnt find that particular one. Thanks for the help and wallaby for that matter.

@lathonez my fears of this not being related to clicker came true. Sorry for the fuss.
