### ISSUE TITLE
Test service with third party library

### ISSUE THREAD

**Issue by EugeneSnihovsky** [lathonez/clicker#183]
Hi. Thanks again for your repo. It is very useful and saves time for me.
Can you help me, please, to test service with third party library (pouchDB)?

pouchDB has typings and it installed in node_modules/@types/pouchDB

App works correct, but when I try to test service with PouchDB I receive an error:

```javascript
TypeError: pouchdb_1.default is not a constructor
```

And console.log show in terminal, that PouchDB is undefined. I think that test missing typings for pouchDB, but can't figure out how to include it correctly.

Service example:

```typescript
'use strict';

import PouchDB from 'pouchdb';
import quickSearch from 'pouchdb-quick-search';
import PouchDbFind from 'pouchdb-find';

PouchDB.plugin(quickSearch);
PouchDB.plugin(PouchDbFind);

import { Injectable } from '@angular/core';
import { CONSTANTS } from '../../constants';

@Injectable()
export class PouchDbService {
    private animalsDb: any = new PouchDB(CONSTANTS.dataBaseName); // this line throw error
    private searchFields: string[] = ['DE_Name', 'EN_Name'];

    public search(query: string): Promise<any> {
        return this.animalsDb.search({
            query: query,
            include_docs: true,
            mm: '50%',
            fields: this.searchFields
        });
    }
}
```

I already ask it on ionic forum, but topic about tests has no action for a long time. I would be glad of any help. Thanks in advance.

**Comment by lathonez** [comment]
I am away for a couple of weeks, will reply on my return.

**Comment by lathonez** [comment]
I'm not sure why you should get that error. I am testing pouch DB in a closed source project fine. However I have mocked pouch and initialise it a separate function so I spy and stub out when testing.

A good example of this is StorageService:

* https://github.com/lathonez/clicker/blob/master/src/services/storage.ts#L14-L16
* https://github.com/lathonez/clicker/blob/master/src/services/storage.spec.ts#L9

This issue https://github.com/lathonez/clicker/issues/169 discusses the concept a bit.

However, I don't see how this would resolve the typings issue. IIRC, the typings for pouch were pretty fiddly?

Is your project open source (can I clone and replicate the issue)?

**Comment by lathonez** [comment]
Closing in favour or #191

**Comment by alexlevy0** [comment]
@EugeneSnihovsky Did you find a solution? Thanks
