### ISSUE TITLE
Configure images and icons for unit testing

### ISSUE THREAD

**Issue by sathyesh** [lathonez/clicker#186]
Hi,

Using Clicker repo I have made work my ionic2 project but still i am getting 404 error for images and icons.Can you please help me on this issue.

Image Location:

WWW/assets/icon/edit.png

In HTML:
`<img src="assets/icon/edit.png">`

**Comment by lathonez** [comment]
I am away at the moment. You probably need to add a proxy to karma
configuration. Google for karma 404. I will be back in a week or so.

**Comment by sathyesh** [comment]
Sorry for the inconvenience, I have figured out after posting here.Will post the solution below.

**Solution:**
