### ISSUE TITLE
Code coverage not working 

### ISSUE THREAD

**Issue by ekoome** [lathonez/clicker#189]
I'm using the configuration on clicker and have tests working but code coverage report is not being generated.

Do I need to activate something to get it going. A quick Google I can see the remap script being run in package.json & setting outdir in tsconfig for generated js files. Do I need to do that?

**Comment by lathonez** [comment]
It works out of the box. See if it's working for you with this repo.

**Comment by ekoome** [comment]
The issue I had is following your blog, I added "ng test" to the package.json file but that was missing mention of option  "--code-coverage". 

That fixed it.

**Comment by kamok** [comment]
Interestingly, my `package.json` contains `"test": "ng test"`, but I'm still able to generate a code coverage.

**Comment by ekoome** [comment]
Wooa magic!

**Comment by kamok** [comment]
When I change `"ng test"` to `"ng test --code-coverage"`, this is what I get:

`The option '--code-coverage' is not registered with the test command. Run `ng test --help` for a list of supported options.`

But yeah, the coverage/index.html is being updated without it. I don't know why, but I'm not complaining.

**Comment by lathonez** [comment]
I've added `--code-coverage` to the blog.

https://github.com/lathonez/clicker/blob/master/package.json#L17
