### ISSUE TITLE
How to mock ViewController.willEnter.subscribe?

### ISSUE THREAD

**Issue by kamok** [lathonez/clicker#190]
When testing components that utilizes the viewController, you must mock the viewController using a viewControllerMock. By the standards of this seeder project, we are placing that class in mock.ts, and importing it in test.ts.

However, I'm having trouble mocking the `willEnter()` method, as even when I return an Observable, as per the docks, it's giving me a `TypeError: viewCtrl.willEnter.subscribe is not a function`.

Has anyone successfully mock these Observables in their app?

Here's my attempt at writing a function that returns an Observable, which returns true when subscribed to it. 

```
public willEnter(): Observable<boolean> {
    let observable = Observable.create(function (observer) {
    observer.onNext(true);
    observer.onCompleted();
    });

    return observable
  };
```

**Comment by lathonez** [comment]
Where are you importing Observable from?

http://stackoverflow.com/questions/36568388/observable-of-is-not-a-function

**Comment by masimplo** [comment]
@kamok willEnter is not a function but an Observable to which you can subscribe. In your mock you can declare it either as a property and set it to and Observable or even better as a getter.

 you can just write 
```
import { Observable } from 'rxjs/Rx';

public get willEnter(): Observable<boolean>{
   return Observable.of(true);
}
```
This will emit a single "marble" with the value `true` and then complete. If you want more fine control you can return a `Subject` instead and feed it with values on demand.

**Comment by lathonez** [comment]
@masimplo - legend.

**Comment by kamok** [comment]
@masimplo That did the trick. Thank you. Posted on stack and nobody knew what to do.

**Comment by lathonez** [comment]
#191
