### ISSUE TITLE
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR

### ISSUE THREAD

**Issue by SelvaAntonyVijay** [lathonez/clicker#192]
In Mean app, when I am running npm test , I amgetting this error

C:\meanprojects\testApp>npm test

> mean@0.7.0 test C:\meanprojects\testApp
> gulp test

Invoking gulp - development
[22:37:38] Using gulpfile C:\meanprojects\testApp\gulpfile.js
[22:37:38] Starting 'startServer'...
[22:38:02] Finished 'startServer' after 24 s
[22:38:02] Starting 'runMocha'...

  0 passing (1ms)

[22:38:03] Finished 'runMocha' after 1.22 s
[22:38:03] Starting 'runKarma'...
10 12 2016 22:38:04.049:WARN [config]: "/" is proxied, you should probably change urlRoot to avoid conflicts
10 12 2016 22:38:09.994:WARN [watcher]: Pattern "C:/meanprojects/testApp/packages/**/public/tests/**/*.js" does not match any file.
10 12 2016 22:38:35.924:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
10 12 2016 22:38:35.926:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
10 12 2016 22:38:36.003:INFO [launcher]: Starting browser PhantomJS
10 12 2016 22:38:51.664:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket /#FR0VJ6pIQnLWMeTnAAAA with id 9688763
::ffff:127.0.0.1 - - [10/Dec/2016:17:09:02 +0000] "GET /_getModules HTTP/1.1" 200 335
::ffff:127.0.0.1 - - [10/Dec/2016:17:09:03 +0000] "GET /api/get-public-config HTTP/1.1" 200 159
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  TypeError: undefined is not a constructor (evaluating '$http.get('/api/users/me').success')
  at app.js:98131
ERROR: 'Possibly unhandled rejection: {}'
ERROR: 'Possibly unhandled rejection: {}'
ERROR: 'Possibly unhandled rejection: {}'
ERROR: 'Possibly unhandled rejection: {}'
ERROR: 'Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/api/users/me","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":""}'
ERROR: 'Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","cache":{},"headers":{"Accept":"text/html"},"url":"meanStarter/views/system/index.html"},"statusText":""}'
PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 0 of 0 ERROR (0.489 secs / 0 secs)
[22:39:04] Finished 'runKarma' after 1 min
[22:39:04] Starting 'stopServer'...

Can any one please help me to solve this issue?

**Comment by lathonez** [comment]
I can't see what this has to do with Clicker at all (closing)
