### ISSUE TITLE
Failed: Can't resolve all parameters for NavParams: (?)

### ISSUE THREAD

**Issue by SoldierCorp** [lathonez/clicker#195]
Hi!

I'm manually compiling the test bed for my component because I had an error using TestUtils but now I have this error:

    Failed: Can't resolve all parameters for NavParams: (?)

I'm calling a function from the construction to get the NavParams I was doing this from the ionViewDidLoad() but since I upgraded to rc3 I had to move all my declarations from ionViewDidLoad() to the constructor.

Do you have any idea?

**Comment by lathonez** [comment]
please see #191

**Comment by AshuSingh07** [comment]
import NavParammock from ionic-mocks and in provider getinstance of NavParamMock as below code sample:

import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import {
  
  NavParamsMock
  
} from "ionic-mocks";
import {GlobalproviderProvider} from "../../providers/globalprovider/globalprovider";
import { ErrorlogPage } from './errorlog';

import {
	IonicModule,
	NavController,
	NavParams
	} from "ionic-angular";

describe('ErrorlogPage (with beforeEach)', () => {
  let component: ErrorlogPage;
  let fixture: ComponentFixture<ErrorlogPage>;
  
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ ErrorlogPage ],
	  imports: [ IonicModule.forRoot(ErrorlogPage)
				 	
	  ],
	  providers:[ 
	  {provide: NavParams, useFactory: () => NavParamsMock.instance()},
		NavController,
		GlobalproviderProvider
		
		
	   ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(ErrorlogPage);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create error component', () => {
    expect(component).toBeDefined();
  });
});
