### ISSUE TITLE
Unmet dependencies of angular-cli

### ISSUE THREAD

**Issue by GerardoRichandez** [lathonez/clicker#199]
I'm using [https://github.com/backand/backand-ionic2-starter] and your project to set up my own project, but I have a problem with the dependencies of angular-cli.
angular-cli depends on @angular/compiler ^2.3.1 but in the package.json is "@angular/compiler": "2.2.1" so, when I do npm install I get 
`npm WARN @ngtools/webpack@1.2.1 requires a peer of @angular/compiler@^2.3.1 but none was installed.
npm WARN @ngtools/webpack@1.2.1 requires a peer of @angular/compiler-cli@^2.3.1 but none was installed.
npm WARN @ngtools/webpack@1.2.1 requires a peer of @angular/core@^2.3.1 but none was installed.
npm WARN @ngtools/webpack@1.2.1 requires a peer of @angular/tsc-wrapped@^0.5.0 but none was installed.
npm WARN @angular/core@2.4.1 requires a peer of rxjs@^5.0.1 but none was installed.
`
and if I do npm list angular-cli I get
`└─┬ angular-cli@1.0.0-beta.24 
  ├── UNMET PEER DEPENDENCY @angular/compiler@2.4.1
  ├── UNMET PEER DEPENDENCY @angular/compiler-cli@2.4.1
  ├── UNMET PEER DEPENDENCY @angular/core@2.4.1
  ├── UNMET PEER DEPENDENCY @angular/tsc-wrapped@^0.5.0
  └── UNMET PEER DEPENDENCY rxjs@^5.0.1

npm ERR! peer dep missing: @angular/compiler@^2.3.1, required by @ngtools/webpack@1.2.1
npm ERR! peer dep missing: @angular/compiler-cli@^2.3.1, required by @ngtools/webpack@1.2.1
npm ERR! peer dep missing: @angular/core@^2.3.1, required by @ngtools/webpack@1.2.1
npm ERR! peer dep missing: @angular/tsc-wrapped@^0.5.0, required by @ngtools/webpack@1.2.1
npm ERR! peer dep missing: rxjs@^5.0.1, required by @angular/core@2.4.1
`

Thanks for your help and I apologize for my poor English. I'm beginning now with Ionic 2 and the documentation is as good ad my English.

**Comment by lathonez** [comment]
Yes unfortunately we're stuck with Ionic being behind on its dependencies.
Hopefully it'll catch up. The alternative is to roll back to a previous
version of ng-cli, but I don't think this is necessary, unless you are
experiencing any actual issues?

**Comment by GerardoRichandez** [comment]
Ok. Thanks for your early answer. I'll try to follow with the project. Thanks again.
