### ISSUE TITLE
support for requirejs

### ISSUE THREAD

**Issue by ciekawy** [lathonez/clicker#20]
This is rather a question as I wonder what are the possible options when the Ionic 2 app code uses some modules that depends on requirejs. 
Currently Ionic 2 app uses any npm modules pretty flawlessly through provided or manually crafted typings. 
I've tried to write a test for such class depending on requirejs module and first thing is to provide somehow the requirejs to the karma. I've added `node_modules/requirejs/require.js` to the `karma.config.js` `files` then needed to add also mappings to `karma.config.js` and `test.main.js` `System.config` and then some other sub-depenecies where missing. I wonder if it would be possible to adapt the way modules are loading into the Ionic app.

**Comment by ciekawy** [comment]
also as there is https://github.com/BugsBunnyBR/ionic2-app-base meant to be the testing concept should we discuss here or there?

**Comment by lathonez** [comment]
Do you have an example module you're working with? I'm not sure I follow you but if I try to import and test it myself I'm sure I will!

Re your second comment, good question. Tagging @BugsBunnyBR in for his thoughts on it. Anything you raise over here will end up over there, so I guess it doesn't matter much.

**Comment by lathonez** [comment]
I found a module `utf8` that seems to depend on requirejs and made a branch demonstrating how I would include it.

https://github.com/lathonez/clicker/compare/requirejs-module-test

The only config changes you need are to karma.config.js.

Let me know if I misunderstand the issue.

**Comment by ciekawy** [comment]
The `utf8` is pretty good example as it is fairly simple.

My case seems quite complex for start yet it would be nice to have. I'm connecting to firebase in my application using [`angular2-firebase`](https://github.com/OasisDigital/angular2-firebase) and I'd like to use also [`MockFirebase`](https://github.com/katowulf/mockfirebase/) with custom typings (like [here](https://github.com/r-park/todo-angular2-firebase)) to do some tests for authentication actually like this:

http://stackoverflow.com/questions/34085020/how-do-i-use-mockfirebase-for-my-angular2-typescript-unit-test

most of the modules are originally plain JS packages requirejs-based so having custom typings may be another degree of complexity.

I've tried to add the libraries to karma and then proxying them in `test-main.js` and I've quickly found there is a lot of cascade requirejs dependencies - i.e. firebase requires `http` `faye-websocket` modules and others. 

So my main concern is to find a way to avoid adding manually to karma config lot of nested dependencies. Maybe it could be possible to kind of mimic current Ionic2 behaviour as all the ordinary JS require based modules integrate without a problem as long as there are appropriate typings provided.

**Comment by lathonez** [comment]
> I've tried to add the libraries to karma and then proxying them in test-main.js

I don't follow why you need to touch test-main.js at all, everything should be proxied in karma.config.js.

> custom typings may be another degree of complexity.

Custom typings are a different topic. I mean it's an answered/closed question, if you need the typings and they don't exist already then you'll need to add them yourself. We've looked at this for another project and found that it's more trouble than it's worth - may not be the case for you.

> So my main concern is to find a way to avoid adding manually to karma config lot of nested dependencies. 

I am not aware of a way to do this. I would be interested in a solution, though I don't consider the work in adding an external module to `karma.config.js` extensive.

However, I will try `angular2-firebase` myself to see what you mean re the complexity. I'm away this weekend so may not get back to you until Monday.

**Comment by ciekawy** [comment]
I don't have detailed knowledge of how requirejs works but from my experience there are some general rules like ie loading `index.js` file or even other specified in package.json of required module. So in general I've got errors when trying to load firebase regarding require being undefined.

It's good the process is already ongoing so there is no hurry and you'd better have a good weekend! ;)

**Comment by lathonez** [comment]
I've included angular2-firebase with a [small change](https://github.com/lathonez/clicker/commit/552453192e566a3cbd0fc425249a8953c2d032bb) in karma.config.js

[full branch compare](https://github.com/lathonez/clicker/compare/requirejs-module-test)

[This doc](https://karma-runner.github.io/0.8/plus/RequireJS.html) has some interesting info re Karma's relationship with RequireJS and test-main.js

**Comment by ciekawy** [comment]
these are good news indeed :) for the unknown reasons some of my installed modules was giving me even more 404. 

After reinstalling all the modules I was not only able to use angular2-firebase but also firebase itself and even [mockfirebase](https://github.com/katowulf/mockfirebase) with some quickly crafted typings.

I'll try to extend your example with mine.

**Comment by lathonez** [comment]
Closing as per #23
