### ISSUE TITLE
Source maps are not working

### ISSUE THREAD

**Issue by ryaa** [lathonez/clicker#203]
Hi,

I created new project from here https://github.com/driftyco/ionic-starter-super and followed the instructions in the blog http://lathonez.github.io/2016/ionic-2-unit-testing/ to enable unit testing however faced couple issues. First, the source maps seems to be generated but when debugging unit tests it is not working. When you click on .ts file it opens js transpiled file - see attached

<img width="1438" alt="screen shot 2017-01-03 at 04 14 38" src="https://cloud.githubusercontent.com/assets/3608222/21598358/aa40a77e-d16c-11e6-9278-83693fefe27d.png">

The other problem is that the test fails because there is an error in ionic slider - see attached
_this.slider is undefined. Not sure why this is happening

<img width="1598" alt="screen shot 2017-01-03 at 04 16 30" src="https://cloud.githubusercontent.com/assets/3608222/21598367/d75c3d7c-d16c-11e6-8554-3b7cf5f124c3.png">

**Comment by lathonez** [comment]
Hey,

So the code coverage generator munges the source maps for some reason. If you run

`ng test`

instead of 

`npm test` (implies --code-coverage)

you should see that the source maps work fine (just checked - I could replicate the behaviour).

If you can give me a link to your repo I'll try to help out with the slider undefined problem (please raise another issue).

Thanks

**Comment by lathonez** [comment]
https://github.com/angular/angular-cli/pull/1799

So basically you can have debug, or coverage, but not both. I'll make it default to debug and do optional coverage

**Comment by lathonez** [comment]
Updated this repo and the blog

**Comment by ryaa** [comment]
Thank you very much for a quick response. I confirm that debugging unit tests works after i removed --code-coverage
I also added another ticket for the second problem https://github.com/lathonez/clicker/issues/204
