### ISSUE TITLE
Test fails because ionic slider undefined

### ISSUE THREAD

**Issue by ryaa** [lathonez/clicker#204]
I created new project from here https://github.com/driftyco/ionic-starter-super and followed the instructions in the blog http://lathonez.github.io/2016/ionic-2-unit-testing/ to enable unit testing. 
The problem is that the test fails because there is an error in ionic slider - see attached
_this.slider is undefined. Not sure why this is happening

<img width="1598" alt="screen shot 2017-01-03 at 04 16 30" src="https://cloud.githubusercontent.com/assets/3608222/21598832/7eb055d4-d174-11e6-800d-80599db76e71.png">

The source code can be found at https://ryaa@bitbucket.org/bossgit/boss811.mobile.git in master branch

**Comment by ryaa** [comment]
Adding fixture.detectChanges() line into test.ts fixed the problem. Here is how it looks now

```
  public static beforeEachCompiler(components: Array<any>): Promise<{fixture: any, instance: any}> {
    return TestUtils.configureIonicTestingModule(components)
      .compileComponents().then(() => {
        let fixture: any = TestBed.createComponent(components[0]);
        fixture.detectChanges();
        return {
          fixture: fixture,
          instance: fixture.debugElement.componentInstance,
        };
      });
  }
```

**Comment by lathonez** [comment]
glad you sorted it

**Comment by lathonez** [comment]
#191
