### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by BugsBunnyBR** [lathonez/clicker#21]
@lathonez , I took a look at ionic-conference-app [package.json](https://github.com/driftyco/ionic-conference-app/blob/typescript/package.json) and the starters... there is no reference to webpack as dependency. Do we really need it? I removed it from clicker and it seems to still work..

**Comment by lathonez** [comment]
We do not, I'll remove it.

I went through the other night and tried to import manually (one by one to see what was actually required).

Should be (on top of iconic base):

* del
* es6-module-loader
* gulp-tslint
* gulp-typescript
* jasmine-core
* karma
* karma-coverage
* karma-jasmine
* karma-mocha-reporter
* karma-phantomjs-launcher
* phantomjs-prebuilt
* systemjs
* traceur
* tslint
* typings

I include other stuff in clicker for travis etc, but just for the testing that should do it.

Deltas (on the clicker side):

* codecov.io (travis)
* coveralls (travis)
* gulp (potentially removable)
* karma-chrome-launcher (travis)
* karma-systemjs (potentially removable)
* tslint-eslint-rules (linting)
* webpack (potentially removable)

I'll nuke the removable stuff and see if it still works!

**Comment by BugsBunnyBR** [comment]
Since travis stuff is not required, it would be good to add a comment in front of each travis dependency in the package.json, just to remember it latter.

**Comment by lathonez** [comment]
You can't comment in JSON unfortunately.
