### ISSUE TITLE
Running tests once

### ISSUE THREAD

**Issue by mebibou** [lathonez/clicker#210]
When running the tests once without modifying the app src files, we could serve the files statically so that we wouldn't have to do `ionic serve`, something like this in `protractor.conf.js`:
```js
  beforeLaunch: function() {
    require('ts-node').register({
      project: 'e2e'
    });

    require('connect')().use(require('serve-static')('www')).listen(8100, function() {
      console.log('Ionic App ready');
    });
  }
```

**Comment by lathonez** [comment]
This looks really cool, thank you.

I will have a play with it and get back to you.
