### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by FJLopezGarcia** [lathonez/clicker#211]
Hi, 
What's the meaning and differences between:
- 64.31% Statements 209/325 
- 5.26% Branches 2/38 
- 29.67% Functions 27/91 
- 64.6% Lines 188/291

I have just created a few .specs and as you can see the coverage is very hight.

Could be just the % of the code you are being testing? if this is the case, what about the rest of files that are not being covering by any unit test, why they don't appear as 0%?

**Comment by lathonez** [comment]
> What's the meaning and differences between:

https://en.wikipedia.org/wiki/Code_coverage (see "Basic Coverage Criteria")

> as you can see the coverage is very hight.

https://github.com/gotwarlost/istanbul/issues/112

More specifically: https://github.com/gotwarlost/istanbul/issues/112#issuecomment-221599706

I haven't checked whether this works here or not. We don't write or maintain the coverage tools, we simply use them (inherited from angular-cli).

Specific questions or issues regarding the coverage tools are probably better raised at the source. Try searching though there is a lot of information out there, check the angular-cli repo for issues too.
