### ISSUE TITLE
Ionic App Scripts overriding ionic serve options

### ISSUE THREAD

**Issue by kamok** [lathonez/clicker#219]
I discovered that there's a number of useful `ionic serve`  command, such as `ionic serve --platform ios` which runs the app with the iOS stylesheets and `Config`. However, using ionic app scripts, and more specifically this line in `package.json`:

` "ionic:serve": "ionic-app-scripts serve"`

Will disable all of those [options](http://ionicframework.com/docs/v2/cli/serve/). 

I haven't dig enough on [ionic app scripts](https://github.com/driftyco/ionic-app-scripts) to see what's the exact utility that it brings, but it seems to be a gotcha that should be made aware.

**Comment by lathonez** [comment]
Interesting. Suggest raising an upstream issue with Ionic if you think the behaviour should be changed. Our package.json comes from their starter app.
