### ISSUE TITLE
Debug information in console.

### ISSUE THREAD

**Issue by svennela** [lathonez/clicker#220]
Hi,

 I am trying to add scripts to start up in clicker project. Not working. How to show below build functionality.

Running live reload server: http://localhost:35729
Watching: www/**/*, !www/lib/**/*, !www/**/*.map
√ Running dev server:  http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

Thank you,
Sri

**Comment by lathonez** [comment]
That seems to be the output from Ionic serve.

Try running `npm test`.

Please read the blog post carefully and try to figure it out yourself.
