### ISSUE TITLE
How to Exclude a folder with typeScript from karma & coverage.

### ISSUE THREAD

**Issue by FJLopezGarcia** [lathonez/clicker#221]
Hi, do you know how to Exclude a folder that contains TypeScripts from karma coverage?

**Comment by lathonez** [comment]
I am AFK this weekend. I don't know if there is a better way than modifying
the regexp in src/test.ts (const context).

You could ask on the Ng-cli repo.

**Comment by emmanuelroussel** [comment]
I added this inside `remapIstanbulReporter` in `karma.conf.js` to exclude set up files from test coverage
```
remapIstanbulReporter: {
  remapOptions: {
    exclude: /src\/(mocks.ts|test.ts|polyfills.ts)/
  }
},
```
You can modify the regex to match the path of the folders you want to exclude.

**Comment by FJLopezGarcia** [comment]
thanks a lot @lathonez lathonez and @emmanuelroussel

**Comment by emmanuelroussel** [comment]
I think you can simply add the rest of the path of `api.ts` and `CompanyApi.ts` to the regex like this
```
/src/(mocks.ts|test.ts|polyfills.ts|app/common/api/api.ts|app/common/api/CompanyApi.ts)/
```
It gets a bit ugly, but it should work.

**Comment by emmanuelroussel** [comment]
@lathonez would like me to make a PR to exclude test config files from test coverage by default?

**Comment by lathonez** [comment]
@emmanuelroussel - I would, but it should be a PR to ng-cli not to us:

https://github.com/angular/angular-cli/issues/3356

**Comment by 1M0reBug** [comment]
@filipesilva provided a new syntax for the `.angular-cli.json` file

[angular/angular-cli#4966](https://github.com/angular/angular-cli/pull/4966)

```json
  "test": {
    "codeCoverage": {
      "exclude": [
        "src/polyfills.ts",
        "**/test.ts"
      ]
    },
    "karma": {
      "config": "./karma.conf.js"
    }
  },
```

**Comment by lathonez** [comment]
@1M0reBug awesome, thanks for the reference. 

Reopening to track merging the upstream change.
