### ISSUE TITLE
Hello I have some problem when I doing npm test

### ISSUE THREAD

**Issue by yandong0475** [lathonez/clicker#222]
some errors occured:

/Users/yandong/Documents/XiaoBaoBaoXiao/XiaoBao/node_modules/@ngtools/json-schema/src/schema-class-factory.js:33
            result.push(...indices);
                        ^^^

SyntaxError: Unexpected token ...

**Comment by lathonez** [comment]
Seems you are having problems testing your own app. Please see #191.

**Comment by lathonez** [comment]
Please accept my apologies. The same issue has just be raised in #223 so obviously is not a problem with your project

**Comment by lathonez** [comment]
Can you replicate this issue by cloning, installing and testing this repo?

If not, there's likely a version difference in one of the packages. Compare the package.json of this project with yours and make sure the versions are the same.

**Comment by marcelofb** [comment]
I solved. The error was the version of node. Here the problem and the solution https://github.com/angular/angular-cli/issues/4604

**Comment by lathonez** [comment]
Thanks.
