### ISSUE TITLE
Coverage is not including all files

### ISSUE THREAD

**Issue by RobertoDebarba** [lathonez/clicker#226]
Hey!

Again, nice work!
Now I am having a issue with test coverage. When I run npm test-coverage the report includes only executed files, but it should include the files who ware not executed with 0% coverage.

Example:
In providers folder I have 3 files: backend.service.ts, clock.service.ts and date.service.ts. I just have test for backend.service.ts, so the other two files dont appear on coverage report and the percent of coverage turn bigger that it realy are.

**Comment by lathonez** [comment]
I can't replicate this behaviour. If I do the following in my repo:

```
rm src/services/clickers.spec.ts
rm -rf coverage
npm run test-coverage
```

I get this in my coverage report:

![screenshot-20170214074655-687x377](https://cloud.githubusercontent.com/assets/7236936/22902652/dd610386-f289-11e6-9540-3474af555645.png)

**Comment by lathonez** [comment]
The issue for you is probably that your file isn't being loaded (included at all) by any of the code that your test is running.

Ultimately, this is an upstream issue for ng-cli:

https://github.com/angular/angular-cli/issues/1735

**Comment by RobertoDebarba** [comment]
Yeah, that's it!

Thanks.
