### ISSUE TITLE
Blog topics links are broken

### ISSUE THREAD

**Issue by Ranhiru** [lathonez/clicker#228]
All 3 links seems to be pointing to non-existent blog posts. Would be really helpful if they can be fixed :)

The only topic I could find in the blog is [this](https://lathonez.com/2016/02/21/unit-testing-an-ionic-2-project/) but it seems to be a completely different file structure from the current repo

**Comment by lathonez** [comment]
Hey,

I'm transferring my domain name so the redirects are broken. Should be fixed this evening.

It's all on lathonez.github.io

**Comment by lathonez** [comment]
Finally all sorted.
