### ISSUE TITLE
upgrade to ionic 2.3.0

### ISSUE THREAD

**Issue by jgallavin** [lathonez/clicker#237]
If you could upgrade the repository to version 2.3.0 of ionic that would help people with the newest version of ionic have confidence that this repository is still being maintained. Thanks

**Comment by lathonez** [comment]
Hi Jason,

We'll be looking at the upgrade early next week. If you'd like to contribute, feel free to make a PR.

Thanks,

Stephen

**Comment by jgallavin** [comment]
I'll see if I can get the time to contribute by next week. If I do feel free to let me know if I'm doing something wrong.

**Comment by lathonez** [comment]
Thanks a lot for your input Jason. It would be great to have a contribution
from you.

Re the broken upgrade on @angular/cli - you really need to make a new app
using the cli and compare everything when upgrading versions. There are
often a lot of config changes. I meld the two apps when I do this.

Same process for Ionic upgrades.

**Comment by murraybauer** [comment]
@lathonez This ionic testing example repo was released recently by ionic themselves with unit tests added and a pending PR to add e2e testing.  May be of use or reference.

https://github.com/driftyco/ionic-unit-testing-example

**Comment by lathonez** [comment]
@murraybauer wow I had no idea this existed! I can finally deprecate this repo. Thanks a lot for the link.

I'm also hoping the Ionic guys will reference all my hard work :sweat_smile:

I'm going to raise an issue to deprecate this repo now.

**Comment by lathonez** [comment]
closing in favour of #239

**Comment by murraybauer** [comment]
@lathonez no probs. It's worth following Max on twitter :-) .  I think we're yet still yet to see an offical announcement.  Appreciate your efforts to date and desire to merge/contribute learnings to hopefully an offical toolkit.
