### ISSUE TITLE
@angular/cli 1.0.0-rc.4 breaks tests

### ISSUE THREAD

**Issue by jgallavin** [lathonez/clicker#238]
for some reason the tests are running in node instead of the browser when upgrading to @angular/cli 1.0.0-rc.4. Do you know why this might be? I will try to do some more troubleshooting.

here are the errors that indicated to me that it was running in node.

ERROR in C:/projects/clicker/src/test.ts (76,24): Cannot find name 'document'.)

ERROR in C:/projects/clicker/src/mocks.ts (98,24): Cannot find name 'HTMLElement'.)
C:/projects/clicker/src/mocks.ts (102,17): Cannot find name 'HTMLDocument'.)
C:/projects/clicker/src/mocks.ts (103,12): Cannot find name 'document'.)
C:/projects/clicker/src/mocks.ts (127,17): Cannot find name 'Window'.)
C:/projects/clicker/src/mocks.ts (128,12): Cannot find name 'window'.)
C:/projects/clicker/src/mocks.ts (144,12): Cannot find name 'document'.)

**Comment by lathonez** [comment]
I have seen this behaviour when re-running tests (e.g. angular/cli's partial rebuild).

Do you see this on first run?

I'd be very surprised if we have any behaviour that @angular/cli do not.

**Comment by lathonez** [comment]
Aside from that I'll take latest angular/cli as part of #237, so you'll need to wait for that.

**Comment by jgallavin** [comment]
that sounds great. It is on first run. After more testing I believe it is rc3 that it breaks on.

**Comment by jgallavin** [comment]
maybe the test bed configuration needs to be moved to another file and imported by the test files themselves? Just shooting ideas here.

**Comment by jgallavin** [comment]
I can confirm that it is breaking on rc3 after incrementing the versions one by one.

**Comment by lathonez** [comment]
closing in favour of #239
