### ISSUE TITLE
StorageMock redundant?

### ISSUE THREAD

**Issue by hfwittmann** [lathonez/clicker#241]
as far as I can tell the code for StorageMock in src/mock.ts is redundant/not used and should probably be removed. Correct?

...
export class StorageMock {

  public get(key: string): Promise<{}> {
    return new Promise((resolve: Function) => {
      resolve({});
    });
  }

  public set(key: string, value: string): Promise<{}> {
    return new Promise((resolve: Function) => {
      resolve({key: key, value: value});
    });
  }

  public remove(key: string): Promise<{}> {
    return new Promise((resolve: Function) => {
      resolve({key: key});
    });
  }

  public query(): Promise<{ res: { rows: Array<{}> }}> {
    return new Promise((resolve) => {
      resolve({
        res: {
          rows: [{}]
        }
      });
    });
  }
}

**Comment by lathonez** [comment]
It's used here: https://github.com/lathonez/clicker/blob/master/src/services/clickers.spec.ts#L10

Query could be removed.

**Comment by lathonez** [comment]
Thanks a lot!

**Comment by hfwittmann** [comment]
Glad to help. After all, this is the best reference for ionic 2 testing.
