### ISSUE TITLE
100% coverage

### ISSUE THREAD

**Issue by hfwittmann** [lathonez/clicker#242]
Hi Stephen,

quick question: do you subscribe to the 100% coverage mantra (as promulgated by e.g. Eran Hammer)?

I suppose the answer is no, since the tests in this project are close to 100%, but not exactly 100%.

Further Remarks: 
I have noticed that e.g. the ionic specific command ionViewDidLoad is not triggered automatically by the component compilation in the unit tests.  I am surprised it is not triggered automatically, do you agree?

It can be done through e.g. 

fixture.componentInstance.ionViewDidLoad();

Is it - in your opinion - useful to do this (in order to achieve the 100%) ?

Cheers, Felix

**Comment by lathonez** [comment]
Hey Felix,

More coverage is obviously better, but I wouldn't break my back to achieve
100% if something was, somehow, untestable.

That

**Comment by lathonez** [comment]
Hey Felix,

More coverage is obviously better, but I wouldn't break my back to achieve
100% if something was, somehow, untestable.

That being said, if you have a PR to increase coverage here it would be
very welcome.

Cheers.

(Sorry I managed to send this early by accident)

**Comment by lathonez** [comment]
Closed in #243
