### ISSUE TITLE
Build failing in travis due to Ionic Cli 3.0

### ISSUE THREAD

**Issue by ValterSantosMatos** [lathonez/clicker#246]
Hi there,

Ionic Cli v3.0 was released and it removed the command ["state"](https://github.com/driftyco/ionic-cli/blob/master/CHANGELOG.md) that is used in the .travis file which causes the build to failed. I didn't had much time to make it work with the cli v3, as a quick fix I just force travis to install the Ionic cli 2.0 instead of the latest one.

From:
`before_install:
  - nvm install node
  - nvm use node
  - npm install -g cordova ionic
  - ionic state clear`

To:
`before_install:
  - nvm install node
  - nvm use node
  - npm install -g cordova ionic@2.2.0
  - ionic state clear`

Ty
Valter

**Comment by lathonez** [comment]
Thanks a lot for this - noticed it in another project but forgot to update here.

**Comment by lathonez** [comment]
b334fe5

**Comment by lathonez** [comment]
b334fe5
