### ISSUE TITLE
e2e testing: error code 100

### ISSUE THREAD

**Issue by charmaine** [lathonez/clicker#249]
Hi! I followed [this](http://lathonez.com/2017/ionic-2-e2e-testing/) tutorial closely but encountered the following error:

#### Protractor e2e testing:
Running `npm run e2e` produces error message 
```
[17:46:39] E/launcher - Process exited with error code 100
npm ERR! code ELIFECYCLE
npm ERR! errno 4
npm ERR! ionic-hello-world@0.0.0 e2e: `ionic-app-scripts build && protractor`
npm ERR! Exit status 4
npm ERR! 
npm ERR! Failed at the ionic-hello-world@0.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

`ionic --version` : `3.0.0-rc.2`
`protractor --version` : ` Version 5.1.2`
`node -v`: `v7.9.0`

I have no idea where to begin in terms of pinpointing where the error is coming from. Any ideas? 

Thanks!

**Comment by lathonez** [comment]
Hey,

Are you able to run the e2e from this repo on your system?

e.g:

```
git clone https://github.com/lathonez/clicker.git
cd clicker
npm install
npm run e2e
```

Thanks,

**Comment by charmaine** [comment]
Yes! I actually ended up just replacing your repo's src file with mine and it worked like a charm. Still not sure why just following the tutorial didn't work, but thanks! :)
