### ISSUE TITLE
AlertController

### ISSUE THREAD

**Issue by hfwittmann** [lathonez/clicker#251]
Hi Stephen,

would you be interested in incorporating an alert/alert controller example? If so, I could provide one (including 100% coverage).

Or would you say: interesting, but this constitutes mission creep?

Cheers Felix

**Comment by kamok** [comment]
What does an alert/alert controller example entail?

**Comment by hfwittmann** [comment]
Among other things it counts/checks the clicks on the elements, such as OK and Dismiss;

**Comment by kamok** [comment]
I just don't understand why you wrote tests. You mean you wrote an AlertController mock? If so I'd be interested in seeing a functional one. I believe currently you can't just import AlertController and use it in your Test Bed.

**Comment by hfwittmann** [comment]
I did, but you are not Stephen, are you?

**Comment by kamok** [comment]
No this is not Stephen. I was just reading the Issues to see if anyone documented an Issue I found.

**Comment by hfwittmann** [comment]
Ok, excellent, I'll wait to hear what he says...

**Comment by lathonez** [comment]
Hey Felix,

I have one too in another project - it was fiddly enough to set it up iirc.

I think it would be helpful. Would be great if you could do a PR? Maybe
something on Page2 that triggers the alert. We've used that page for
examples like that in the past.

Cheers

**Comment by hfwittmann** [comment]
Excellent, I'll get onto that, probably today..

**Comment by lathonez** [comment]
closed in #252 thanks a lot Felix
