### ISSUE TITLE
Can we do unit testing of Forms, Navigations using official Ionic-unit-testing example?

### ISSUE THREAD

**Issue by jainAdijain** [lathonez/clicker#258]
Hi Lathonez,
I have read your blog which was very explanatory and useful.
I know this platform is not good for these types of questions but I am not able to add more questions to stackoverflow.
I am very new to Karma/jasmine and using my hand for Unit Testing of Ionic Application. I have some questions which I felt that you can only give me a correct answer and guide me to solve those.
1.) As I want to test unit testing of forms on ionic, so the official unit-testing-example of ionic will be okay or shall I use clicker because I have to decide if unit-testing is possible then only I can include in production.

2.) In Unit-testing for ionic applications there are only limited use cases? Like for example I want to unit test a form so there limited no of use cases or we can test any use case that we are willing to?And If there are limited then is there any list for those?

3.)Is ionic have there own utils methods as that of angular's utility methods?If yes then where do we find the lists?

Thank you, Hope you will reply.

**Comment by lathonez** [comment]
Hi,

1 - I would not use unit-testing-example for production code

2 - You can test anything you want

3 - Not that I am aware of

Thanks

**Comment by jainAdijain** [comment]
okay, Thank you for the response.
