### ISSUE TITLE
Add support for multiple languages

### ISSUE THREAD

**Issue by stonelasley** [lathonez/clicker#268]
Any interest in adding this to the app? I have a couple other apps using [ngx-translate](https://github.com/ngx-translate) and would be happy to submit a PR.

**Comment by hfwittmann** [comment]
I think this is a good suggestion, I was just about to suggest this myself! I have a solution , too, but there are quite a few files affected, maybe you have something better/simpler
Felix

**Comment by hfwittmann** [comment]
... just my personal opinion, of course, Felix

**Comment by lathonez** [comment]
yep great idea. Sorry I'm super busy at the moment but will get onto it ASAP.

**Comment by lathonez** [comment]
closed in #280
