### ISSUE TITLE
Ionic deeplinks

### ISSUE THREAD

**Issue by hfwittmann** [lathonez/clicker#269]
Are there any plans to add support for deeplinks (with @IonicPage() and  IonicPageModule ) ?

Felix
PS
I have something working, but can't achieve 100% coverage ( in a scenario for a page using a component)

**Comment by hfwittmann** [comment]
I have actually got a version to work, with 100& coverage, but it's little cumbersome ...

**Comment by hfwittmann** [comment]
I've now found a more elegant way, for an implementation of multi-language support. https://github.com/lathonez/clicker/issues/268
I would also be happy to supply a PR,

Cheers Felix

**Comment by lathonez** [comment]
Think this can be closed in favour of #268? Please re-open if not.

@hfwittmann - not sure if you're up for collaborating with @stonelasley on #271 - I have ~zero experience with ng-translate but happy to get stuck in with the CI / testing side.
