### ISSUE TITLE
Getting a '404' for -> http://lathonez.com/2017/ionic-2-unit-testing/

### ISSUE THREAD

**Issue by Robinyo** [lathonez/clicker#281]
Hi,

Getting a '404' for -> http://lathonez.com/2017/ionic-2-unit-testing/

Cheers
Rob

**Comment by lathonez** [comment]
Thanks - somehow I updated the posts to be 2018.

https://github.com/lathonez/lathonez.github.io/commit/b85fc2592fbc930dbcac826d0058d187dff6447d
