### ISSUE TITLE
Undesirable Warning: Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by martialp** [lathonez/clicker#282]
I get this Undesirable warning 4 times when running `npm test`:

```
WARNING in ./node_modules/ionic-angular/es2015/util/ng-module-loader.js
25:11-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/ionic-angular/es2015/util/ng-module-loader.js
 @ ./node_modules/ionic-angular/es2015/util/module-loader.js
 @ ./node_modules/ionic-angular/es2015/components/modal/modal-component.js
 @ ./node_modules/ionic-angular/es2015/index.js
 @ ./src/test.ts
```

**Comment by lathonez** [comment]
https://github.com/angular/angular/issues/11580

I don't want to add a webpack config file I need to maintain to remove this warning. You can do yourself if you want to:

* It isn't clear that there are any adverse side affects from the warning
* ng-cli are working on solving it anyway - ultimately we will get a fix from upstream and not need to apply it in config
