### ISSUE TITLE
Questions about E2E test cases for Ion-menu component

### ISSUE THREAD

**Issue by Abhishek-Kanitkar** [lathonez/clicker#283]
Hi @lathonez ,

First of all, thanks a lot for all your efforts for this repo. It's great help to all of us.

I am trying to do E2E tests for ion menu component that I am using in my project.

Following are the scenarios I am trying to test with Protractor & Jasmine.

1) On click of a menu item, the menu collapses.
2) On tap out of menu / on click of menu back drop, the menu should collapse too.

Somehow I just am not able run the E2E tests with success.

Can anyone please show me code for E2E tests that covers above scenarios ?

Please help me !

**Comment by lathonez** [comment]
Hey, see #191 

Cheers
