### ISSUE TITLE
 Error: Uncaught (in promise): invalid link: rootPage in case of lazy loading unit test cases

### ISSUE THREAD

**Issue by oporje** [lathonez/clicker#284]
My application is lazy loaded with LoginPage as rootPage and I have menu is my app component.

When I am writing unit test cases for the app component and do fixture.detectChanges();

 Error: Uncaught (in promise): invalid link: LoginPage
It throws above error.

**Comment by lathonez** [comment]
Please see #191

**Comment by lathonez** [comment]
Please see #191
