### ISSUE TITLE
Usage of Greenkeeper 

### ISSUE THREAD

**Issue by riderx** [lathonez/clicker#286]
You use david's to know if the dependencie are up to date but you can have greenkeeper who make alone the Pr with new npm version. 
So with the CI you will know if the update can be made or not, without any work  :) 
https://greenkeeper.io/

**Comment by lathonez** [comment]
hey @ric9176 

Sorry for not responding to you, I lost this in all my emails.

I find that greenkeeper and Ionic don't really work well together (at least of Ionic 3x) as we're often tied, by Ionic to outdated versions of things. I guess one good example being `@angular`.

I do use greenkeeper with other projects and think it's a great tool.

As of Ionic 4, greenkeeper may work better, but then as of Ionic 4 this project will probably be redundant anyway, as angular cli should work out of the box with Ionic.

Thanks,

Steve
