### ISSUE TITLE
Ionic Serve does not work.

### ISSUE THREAD

**Issue by udayakanth1122** [lathonez/clicker#29]
After following all the instructions and resolving issues, I got the karma-jasmine unit tests working.
But when I run "ionic serve", a blank webpage is opened.

For some reason app.bundle.js is not generated under "www/build". 

Also I noticed that in the tutorial
[22:54:02] Starting 'test.build'...
**[22:54:04] TypeScript: emit succeeded**  <---- this appears
[22:54:04] Finished 'test.build' after 1.88 s

when I run this is what i see

[23:43:08] Starting 'test.build'...
[23:43:11] Finished 'test.build' after 2.64 s   <-- typescript: emit success message is missing.
[23:43:11] Starting 'startKarma'...

Error:
 http://localhost:8100/build/js/app.bundle.js  is throwing a 404 error.

Can someone please help me resolve this?

Thanks!

**Comment by lathonez** [comment]
Upgrade your version of ionic to latest.

`npm install -g ionic@beta`

You should have:

```
x220:~/code/clicker$ ionic --version
2.0.0-beta.19
```

**Comment by lathonez** [comment]
Please reopen if this doesn't / hasn't fixed your issue.

**Comment by udayakanth1122** [comment]
installing ionic@beta worked for me. Thanks!
