### ISSUE TITLE
upgrade script / checklist

### ISSUE THREAD

**Issue by lathonez** [lathonez/clicker#30]
There's getting to be a lot of things to check each time ionic do an upgrade (#28). It'd be good to have a script / list of stuff to check each time.

**Comment by lathonez** [comment]
* review node_modules/ionic-angular/index.js
* review package.json
* review typings.json
* take new ionic.config

**Comment by marcmeans** [comment]
If you have a roadmap of ideas you're looking to do too, I can contribute some.

**Comment by lathonez** [comment]
Hey @marcmeans,

Not sure what you mean re roadmap.

The purpose of this task is to try to make sure we don't miss things when upgrading to the next Ionic version. I was thinking of scripting something up eventually, probably when the next version is out.

With regard to the wider project, Angular 2 seed have some cool stuff since I forked that I really want to implement here (#19).

After that I'll look at developing the app further as a more complete demo and releasing it in the app stores, hopefully with travis and blog posts.

Other than that it's just trying to stay on top of the Ionic changes.

If you've seen anything cool that you think would be worth putting in here raise an issue for it and we'll discuss it there.

Top of my list now is figuring out how [this](https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency) works. For us we have to proxy in `karma.config.js` too, not looked into it yet - porting the `gulpfile` to *.ts was prep.

**Comment by lathonez** [comment]
@marcmeans - I didn't see your edited comment until just now. I'll get back to you tonight.

**Comment by lathonez** [comment]
In the end, I think the only way of doing this at the moment is to create a new ionic starter and meld.

The advice from Ionic on this beta (3) was to move code over. So I guess you just have to meld / diff and look at all diffs.
