### ISSUE TITLE
server response 404 app.bundle.js

### ISSUE THREAD

**Issue by gustav77** [lathonez/clicker#32]
just cloned your project, great work. Thank you.

I got an issue on npm start: server response 404, can't find app.bundle.js

I can't figure out what I am missing, all unit tests are fine, no errors. 

Thanks for your help.

Guenter

**Comment by lathonez** [comment]
Hey Guenter,

What version of ionic are you running?

See #29 

Cheers

**Comment by gustav77** [comment]
thank you, I actually had beta.17, now beta.19 fixed the issue

**Comment by lathonez** [comment]
No worries - had the same problem when I upgraded to ionic-angular@beta.2
