### ISSUE TITLE
How to run one test file

### ISSUE THREAD

**Issue by BugsBunnyBR** [lathonez/clicker#35]
What's up doc? Do you see a way to execute only one test file? I mean, many times I am writing my tests and want to see if one specific test will fail or not and the whole process of build project and run all tests can take some time.

**Comment by lathonez** [comment]
Hey!

Changing [this filter](https://github.com/lathonez/clicker/blob/master/test/test-main.js#L46-L48) is the only way I've come across.

For example:

```javascript
function onlySpecFiles(path) {
  return /app[\.|_]spec\.js$/.test(path);
}
```

Will only run `app.spec.ts`

Another project I'm working with this setup on has ~150 tests. I found yesterday that using the new watch functionality makes adding tests and debugging a lot quicker. Give it a try before if you've not already.

**Comment by lathonez** [comment]
I found [this](https://github.com/karma-runner/karma/issues/553#issuecomment-176938995) today which works well.
