### ISSUE TITLE
ionic-app-lib throws exception on test run

### ISSUE THREAD

**Issue by marcmeans** [lathonez/clicker#36]
I think removing the ionic-app-lib from the package.json made the tests fail when trying to access that lib.  I only saw this when I dropped my npm folder and ran npm install fresh.  The old folder was supporting the global working.  I verified this with a fresh clone as well.

I can do a PR to put the lib back in packages, but didn't know if you knew of an alternate fix.

**Comment by lathonez** [comment]
Thanks for raising this. I'd really like to get to the bottom of it (I have the same issue on Travis, but not locally).

I'm happy enough to put the module back in as a dev dependency. However, I see it like having the Ionic CLI or Android tools as a dev dependency, plus the thing is massive, so I'd like to avoid it.

I've just done this:

```
rm -rf clicker
git clone git@github.com:lathonez/clicker.git
cd clicker
npm install && ionic state restore
npm test
```

I tried something similar before when I removed ionic-app-lib to a global dependency. All good for me. Now I'm sure it is broken for you as it's broken for me on travis, I just want to know why.

What do you get if you do the following

```
cd /tmp
node
> require ('ionic-app-lib');
{ assets: [Getter],
  browser: [Getter],
  configXml: [Getter],
  config: [Getter],
  cordova: [Getter],
  events: [Getter],
  hooks: [Getter],
  info: [Getter],
  ioConfig: [Getter],
  logging: [Getter],
  login: [Getter],
  multibar: [Getter],
  package: [Getter],
  ports: [Getter],
  project: [Getter],
  release: [Getter],
  resources: [Getter],
  security: [Getter],
  serve: [Getter],
  settings: [Getter],
  setup: [Getter],
  share: [Getter],
  start: [Getter],
  state: [Getter],
  stats: [Getter],
  store: [Getter],
  task: [Getter],
  templates: [Getter],
  upload: [Getter],
  utils: [Getter],
  v2: 
   { build: [Getter],
     project: [Getter],
     serve: [Getter],
     start: [Getter] },
  semver: [Getter] }
> 
```

**Comment by lathonez** [comment]
After reading this [SO](http://stackoverflow.com/questions/7970793/how-do-i-import-global-modules-in-node-i-get-error-cannot-find-module-module) I'm trying this ea50a6a.

If it [builds okay](https://travis-ci.org/lathonez/clicker/builds/114619089) it should be all good for you too.

**Comment by marcmeans** [comment]
I had uninstalled my global ionic-app-lib trying to get this running.  I did notice when I went to install it again that it gave me this error, though it still continued.

npm ERR! gentlyRm containing path /Users/marcmeans/.npm-packages/lib/node_modules/ionic-app-lib/node_modules/fsevents/node_modules/node-uuid isn't under npm's control

✘  ~/dev/tmp  node
> require ('ionic-app-lib');
Error: Cannot find module 'ionic-app-lib'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:281:14)
    at REPLServer.runBound [as eval] (domain.js:294:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:83:20)

**Comment by lathonez** [comment]
OK let's see what happens with this build (forgot to sudo on the last one).

https://travis-ci.org/lathonez/clicker/builds/114625761

And/Or just clone the repo and see if npm install works

**Comment by lathonez** [comment]
Finally:

https://travis-ci.org/lathonez/clicker/builds/114632328

Working now for me on travis installed globally. How is it for you?

**Comment by lathonez** [comment]
I'm gonna close this as Travis is now working. If it's still for you re-open!
