### ISSUE TITLE
Typescript maps for debug/coverage

### ISSUE THREAD

**Issue by lathonez** [lathonez/clicker#39]
No idea how to implement this!

**Comment by lathonez** [comment]
@marcmeans - any ides on this?

**Comment by marcmeans** [comment]
let me take a peek and see.

**Comment by lathonez** [comment]
https://www.npmjs.com/package/karma-sourcemap-loader

**Comment by masimakopoulos** [comment]
I so badly need this. Have you given karma-sourcemap-loader a try @lathonez and didn't work or are you just keeping notes?

**Comment by marcmeans** [comment]
I started to look at it.  But with the upgrade to beta4 in ionic2 I've gotten distracted.  I have this on my list to look at in the next week still.  If I can get it working I'll let you know.

**Comment by masimakopoulos** [comment]
@marcmeans awesome, please keep us posted. Will take a look myself after I upgrade my project to the latest libraries to see if I can get any insights.

**Comment by lathonez** [comment]
@masimakopoulos - I forget where that reference come from, someone on this repo was using it but I don't know to what degree of success.

@marcmeans - appreciate that you're still trying to look at this. I've been busy recently. As of last night everything in this repo should be latest.

If you have no time let me know and I'll pick it up

**Comment by masimakopoulos** [comment]
@lathonez I see the [repo](https://github.com/bengro/ionic-seed-example) mentioned in https://github.com/lathonez/clicker/issues/58 uses karma-sourcemap-loader [here](https://github.com/bengro/ionic-seed-example/blob/master/package.json#L27) and [here](https://github.com/bengro/ionic-seed-example/blob/master/karma.conf.js#L38), but not sure if it actually works.

**Comment by lathonez** [comment]
I've just used it briefly tonight in the 'lightweightify' branch on this
repo. Nothing conclusive yet but the basic functionality seems to be there.
The missing piece of the puzzle for me is generating the .map files at
compile time. Presumably it's just an option to tsc, not looked yet.
On 14 Apr 2016 20:51, "Michael" <notifications@github.com> wrote:

@lathonez <https://github.com/lathonez> I see the repo
<https://github.com/bengro/ionic-seed-example> mentioned in #58
<https://github.com/lathonez/clicker/issues/58> uses karma-sourcemap-loader
here
<https://github.com/bengro/ionic-seed-example/blob/master/package.json#L27>
and here
<https://github.com/bengro/ionic-seed-example/blob/master/karma.conf.js#L38>,
but not sure if it actually works.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/lathonez/clicker/issues/39#issuecomment-209834534>

**Comment by lathonez** [comment]
@marcmeans - I'm kinda working on this as a by-product of #68

**Comment by masimakopoulos** [comment]
@lathonez aren't the maps being generated by ionic-gulp-browserify-typescript? I see this in their source code:

```
var sourcemapPipe = lazypipe()
    .pipe(buffer)
    .pipe(sourcemaps.init, { loadMaps: true })
    .pipe(sourcemaps.write, './');
```
and a few lines later

```
return b.bundle()
      .on('error', options.onError)
      .pipe(source(options.outputFile))
      .pipe(gulpif(options.browserifyOptions.debug, sourcemapPipe()))
      .pipe(gulp.dest(options.outputPath));
```

So if I am understanding this correctly, source maps are generated if browserify debug mode is true. Which from the same file 
```
  browserifyOptions: {
    cache: {},
    packageCache: {},
    debug: true
  },
```
seems to be true by default.

**Comment by lathonez** [comment]
Yeah this is fine when bundling the spec. Not sure if we're going down that
road yet.

**Comment by lathonez** [comment]
As per #68 sourcemaps are now available @ `test.bundle.js.map`
