### ISSUE TITLE
Build location for custom images

### ISSUE THREAD

**Issue by lathonez** [lathonez/clicker#40]
I think images should go in `resources/images` as the resources folder comes from Ionic. If the user has images in a different folder it'll be easy enough for them to change / add the location based on this as an example.

After that we just need to add it to Karma.

So:

* add some image and include it on a clicker page
* test said page
* should get a 404 from Karma
* add images to karma

**Comment by BugsBunnyBR** [comment]
Looking at [conference-app structure](https://github.com/driftyco/ionic-conference-app/tree/typescript/www/img)
they seems to use `www/img` not carrying about image density which is very odd to me... I don't know how 'default' or 'good pattern' it is... Looking at the conference issues I found this https://github.com/driftyco/ionic-conference-app/issues/98

**Comment by lathonez** [comment]
Interesting. My TL;dr from that issue is:

* keep images separate from app folder
* don't copy images at build time (hence putting them in `www`)

Works for me anyway.

**Comment by masimakopoulos** [comment]
I am following the same approach. Images, custom fonts etc are stored directly in the www folder. I do not find a value of copying them (or even process them) in every build. Images should be optimised once before going into the www folder and that's it. 
Only issue with this is getting the paths right for referencing images, especially inside css, but once figured out, it works well.

**Comment by lathonez** [comment]
Thanks, appreciate the input.

**Comment by lathonez** [comment]
There didn't actually seem to be much to do in the new set up. I've added an image to page2 just for the purposes of this issue really.

Karma doesn't complain about a 404 and protractor sees the image fine.

went with `www/images` as suggested.

Reopen if I'm missing something or there's more to do.

**Comment by mbakker96** [comment]
`www/assets/images` is in my eyes the best solution. I have in my assets folder also my mock JSON files

**Comment by lathonez** [comment]
Thanks. Personally I don't see the need for another folder under `www`, similar to what [Ionic do](https://github.com/driftyco/ionic-conference-app/tree/typescript/www), I just don't like abbreviations for no reason (images instead of img).

This stuff is really subjective. The purpose of this issue was to get a working solution which is easily customisable if you want to use a different path. In the end there wasn't much that needed doing tbh.
