### ISSUE TITLE
Unit test @Pages

### ISSUE THREAD

**Issue by lathonez** [lathonez/clicker#41]
Similar to the component tests, we should be testing @Pages properly using DI so we can inspect the DOM during the tests.

**Comment by bengro** [comment]
Is this issue addressing the fact, that implementation using and linking the @Page cannot be tested? I would be very much interested in solving this asap - do you have pointers of where to get started?

**Comment by lathonez** [comment]
@bengro - exactly, I've got it up and running in another project, will try to add something quickly..

**Comment by bengro** [comment]
That would be most splendid! If I can do something to speed things up, let me know. I'm assuming the problem is the transpilation/systemjs? I'm keen on seeing how you solved the problem. My first step would have been to find out how @Component does it.

Thanks a bunch @lathonez!

**Comment by lathonez** [comment]
@Page is the same as @Component with more dependencies

65bf5d5

I've set up the skeleton for the ClickerList @Page. This should give you access to the 'clickerListComponentFixture' variable, through which you can get the page DOM.

I found [this blog](https://developers.livechatinc.com/blog/testing-angular-2-apps-dependency-injection-and-components/) really useful when I set it up for @Components in the first place.

**Comment by bengro** [comment]
Very helpful, thank you.

**Comment by ciekawy** [comment]
slightly OT, how does current gulpfile/webpack corresponds to previous test config? does it still execute tests or needs to be reenabled?

**Comment by lathonez** [comment]
Sorry, could you elaborate a little?

**Comment by ciekawy** [comment]
I've found an answer. I haven't noticed dedicated gulpfile for tests and github diff showing only the differences :) On my project I've managed to easily merge the gulpfile used only for testing with the new one generated by recent ionic cli.

**Comment by lathonez** [comment]
Cool. I wanted to keep the testing one separate to make things more obvious, particularly as the main one is maintained by Ionic. As you say they are easily merged.

**Comment by lathonez** [comment]
Didn't mean to close

**Comment by fmsouza** [comment]
Within *angular@2.0.0-rc-1* the `@Page` decorator was deprecated. Now there's only the `@Component` decorator for this purpose.

**Comment by lathonez** [comment]
@fmsouza yup. I guess this issue is basically dead now. I still feel that there could be more examples of DOM testing components in this project, but we really need more complicated pages (#44 / #45) in order to address that.
