### ISSUE TITLE
E2E Testing with Protractor

### ISSUE THREAD

**Issue by lathonez** [lathonez/clicker#42]
Angular 2 seed have a good set up we can hopefully borrow

**Comment by lathonez** [comment]
Looking at this now

**Comment by lathonez** [comment]
groundwork: fd563d56158d02ba0ccaa4eab51770e3ed46828d

**Comment by lathonez** [comment]
#50

**Comment by lathonez** [comment]
So since #50, all we need to do is:

* move app.e2e.js to typescript inside the source folder
* compile above to js in gulp
* integrate with Travis

**Comment by mebibou** [comment]
FYI, if you add those lines in your `protractor.conf.js`, you don't need to do `npm run webdriver-start` anymore:
````
seleniumAddress: 'http://localhost:4444/wd/hub',
seleniumPort: 4444,
chromeDriver: '../node_modules/protractor/selenium/chromedriver'
````

**Comment by lathonez** [comment]
Thank you, will give it a go.

**Comment by mebibou** [comment]
Also, I don't know if you know [ripple-emulator](https://github.com/ripple-emulator/ripple), but it allows you to run your app like an Android or iPhone app with some Cordova features (or writing your own bridges if you need more). Here's my full `protractor.conf.js` to give you an idea:
````
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  seleniumPort: 4444,
  chromeDriver: '../node_modules/protractor/selenium/chromedriver',
  directConnect: true,
  framework: 'jasmine2',
  baseUrl: 'http://localhost:8100',
  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      args: ['--disable-web-security']
    }
  },
  specs: [
    'protractor/**/*.js'
  ],
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30 * 1000,
    isVerbose: true
  },
  onPrepare: function() {
    // Use ripple emulator to run the tests
    var url = 'http://localhost:4400/?enableripple=cordova-3.0.0-' + browser.params.device;
    browser.driver.manage().window().maximize();
    browser.ignoreSynchronization = true;
    browser.driver.get(url);
    // Allow ripple to load
    browser.driver.wait(function() {
      return browser.driver.getCurrentUrl().then(function(actualUrl) {
        return url == actualUrl;
      });
    }, 10000, 'url hasnt changed');
    browser.driver.wait(function() {
      return element(by.id('document')).isPresent();
    }, 10000, 'ripple not loaded');
    browser.driver.switchTo().frame(0);
  }
};
````

Although this used to be working before, since I updated to `ionic2-beta.3` it doesn't work anymore :disappointed:

**Comment by lathonez** [comment]
I don't, again thank you. I have basically zero experience with Protractor and E2E testing generally, so this is a big learning curve for me and I appreciate the advice.

You don't have a public repo with this in by any chance?

**Comment by mebibou** [comment]
Ah sorry I don't for now, but I could probably do something simple when I find the time for it

**Comment by lathonez** [comment]
No worries. Hopefully I will be able to get your suggestions in this and they will help some other people.

**Comment by lathonez** [comment]
Removing webdriver-start works well, thank you very much.

c5d3a46

Also raised #52 for ripple when I get round to it.

**Comment by mebibou** [comment]
eheh nice

**Comment by lathonez** [comment]
https://travis-ci.org/lathonez/clicker/builds/116036958
