### ISSUE TITLE
travis-ci deploy asks for passphrase.

### ISSUE THREAD

**Issue by udayakanth1122** [lathonez/clicker#46]
I got the build setup on travis and have successfully been able to launch it. The part where Im having difficulty is with the deployment to apps.ionic. I followed the encryption mechanism that travis-ci provides and was able to create a .enc file. I followed automated encryption: https://docs.travis-ci.com/user/encrypting-files/. The rest of the code is pretty much the same. When I try to deploy, I see a prompt for a passphrase in travis. Obviously I cannot enter anything.

 Im not sure what I'm doing wrong. I need a little bit of education regarding this. Also when I use the file for encryption, what do I need to put in the file?

Please help me.

**Comment by lathonez** [comment]
Yes it is a little fiddly, took me a while to get set up in the first place.

* Do you have a repo I can look at?
* Which file did you encrypt?

**Comment by udayakanth1122** [comment]
this is the repo i have been working on
https://github.com/udayakanth1122/ionic2-karma-jasmine-travis-seed 

under .travis, im using the file with .enc extension.

I made a file with a phrase in it and encrypted that file using "travis encrypt-file" command.

I'm not sure if that phrase needs to match with the github ssh key phrase. That's where im stuck at.

**Comment by lathonez** [comment]
Interesting concept :)

From memory, you need to generate an ssh key pair, encrypt the private key and add the public key to your git hub.

**Comment by udayakanth1122** [comment]
Ok ill try that out.
I saw your build and for "Setting environment variables from repository settings" where with in your code structure, are you encrypting ionic username, password, app id and name?

**Comment by lathonez** [comment]
My environment variables are:

* IONIC_EMAIL
* IONIC_PASSWORD
* IONIC_APP_ID
* IONIC_API_KEY

(and then the encrypted key and IV that's auto-added by travis when you encrypt a file).
