### ISSUE TITLE
Broken build: ionic-app-lib.d.ts is gone

### ISSUE THREAD

**Issue by jasonwaters** [lathonez/clicker#53]
My travis ci build broke recently due to this file disappearing:  https://raw.githubusercontent.com/lathonez/typings/master/ionic-app-lib.d.ts

Looks like you are making some changes to your repo here, which is good.  I'd like to update my test suite to follow suite.  But in the meantime can I get the contents of that file?  I need my build to run :grimacing:

**Comment by lathonez** [comment]
Yeah I've removed the dependency, which is really good as it was disgusting.. Apologies I didn't think through removing the typings repo.

```
declare module "ionic-app-lib" {
  module IonicAppLib {
    var v2: any;
  }

  export = IonicAppLib;
```

**Comment by jasonwaters** [comment]
when do you expect to wrap up your latest refactor?

**Comment by lathonez** [comment]
It's stable now. No plans to change the unit testing structure.
