### ISSUE TITLE
add www/build/ in gitignore

### ISSUE THREAD

**Issue by BugsBunnyBR** [lathonez/clicker#54]
hey, should https://github.com/lathonez/clicker/tree/master/www/build/ go to gitignore ?

**Comment by mbakker96** [comment]
I have it also in my gitignore because you want to build it when you run `ionic serve`

**Comment by lathonez** [comment]
It is - https://github.com/lathonez/clicker/blob/master/.gitignore#L25

I think you are probably referring to the compiled tests being pushed at compile time - https://github.com/lathonez/clicker/blob/master/.travis/push_built_tests.sh#L13

Which gives you this - https://coveralls.io/builds/5417429/source?filename=www%2Fbuild%2Ftest%2Fservices%2Futils.js

I have been thinking about removing this and just having a gulp task to serve the coverage locally. Which makes using coveralls / codecov somewhat moot.

Thoughts?

**Comment by BugsBunnyBR** [comment]
Cant you compile the code at travis and then send to coverall? I don't know the service...

**Comment by lathonez** [comment]
Not to my knowledge.

**Comment by lathonez** [comment]
Could potentially use this and move it to a different folder to stop it interfering with the build?

https://codecov.io/github/lathonez/clicker/features/fixpaths

**Comment by BugsBunnyBR** [comment]
it is kinda weird, coveralls says something about building at travis [here](https://coveralls.zendesk.com/hc/en-us) and has [this](https://coveralls.zendesk.com/hc/en-us/articles/201769715-Javascript-Node) docs but I could not follow...

**Comment by lathonez** [comment]
I've found codecov to be better as it gives you branch coverage. Leave it with me.

**Comment by lathonez** [comment]
I've it to coverage/source/test, which I hope will be less invasive. If this isn't the case let me know.

The paths thing in codecov worked well:

https://codecov.io/github/lathonez/clicker/coverage/source/test/components/clickerButton/clickerButton.js?ref=32923e30b92f76aeda3b8938a234b974f8e14978
