### ISSUE TITLE
cannot find module 'express-serve-static-core'

### ISSUE THREAD

**Issue by ramogundogdu** [lathonez/clicker#57]
After I downloaded your project the command `node_modules/gulp/bin/gulp.js --gulpfile test/gulpfile.ts --cwd ./ test.build` can not be executed. I get an error: `Unable to compile TypeScript` `cannot find module 'express-serve-static-core'` How can I solve the Problem?

**Comment by lathonez** [comment]
If you are downloading the project from scratch you can just run npm instsall as per the [readme](https://github.com/lathonez/clicker/blob/master/README.md).

```
git clone https://github.com/lathonez/clicker.git
cd clicker
npm install       # or `npm run reinstall` if you get an error
npm start         # start the application (ionic serve)
npm test          # run unit tests
```

Does this work for you?

The blog post is meant to be a step-by-step for how you could import the framework into an existing project

**Comment by ramogundogdu** [comment]
Unfortunately not. I get the same error

**Comment by lathonez** [comment]
OK. As it is happening on Travis I think it must be an issue with your setup.

I actually can't find references to that module anywhere? Does this grep return anything for you? Inside my repo..

`grep -rns express-serve-static-core *`

**Comment by ramogundogdu** [comment]
The return of `grep -rns express-serve-static-core *`:

![bild 1](https://cloud.githubusercontent.com/assets/5772401/13925171/a2104248-ef87-11e5-97ac-3351b92308e3.png)

**Comment by ramogundogdu** [comment]
I downloaded the project again. It worked this time. Thanks.

**Comment by shirakaba** [comment]
I experienced this error in a `ts-node` project due to my globally-installed Node (which `ts-node` depends upon) being out-of-date (v4.8.7). I updated it to v8.9.4 and it worked fine.

Perhaps that this newer version of `express-serve-static-core` uses newer ECMAScript features that the old Node doesn't understand, indirectly causing its import to fail.
