### ISSUE TITLE
Readme e2e test

### ISSUE THREAD

**Issue by CarlosAdrianM** [lathonez/clicker#64]
It is not a code issue, but a "readme" one.

In readme file:
```
Run E2E

# e2e (aka. end-to-end, integration) - In three different shell windows
# Make sure you don't have a global instance of Protractor

# npm run webdriver-update <- You will need to run this the first time
npm start
npm run e2e

```
Which three different shell windows? Maybe it is not clear enough, but I am not able to run E2E tests...

**Comment by lathonez** [comment]
Hey, you only need two windows as we've removed a step.

69b5ccb

In one window: `npm start` in another `npm run e2e`

http://lathonez.github.io/2016/ionic-2-e2e-testing/
