### ISSUE TITLE
404: npm ERR! Test failed.

### ISSUE THREAD

**Issue by ramogundogdu** [lathonez/clicker#70]
I get the following output after the `npm test` .

I have some modules in my app and in each modules a index.ts file. This index files aren't considered while the process of built. The structure of the folders looks like the following:

e.g. module 1:
```
app/modules/calender/calender.html
app/modules/calender/index.ts
```

e.g. module 2:
```
app/modules/testModule/calender2.html
app/modules/testModule/index2.ts
```
etc.

`import {Calender} from './modules/calender/';` In this case, it isn't looked for the Files after `..calender/`. For this is added just `.js` behind the `/` .

How can I bypass this error?
```
START:
11 04 2016 13:47:14.841:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
11 04 2016 13:47:14.841:INFO [launcher]: Starting browser PhantomJS
11 04 2016 13:47:16.613:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket /#JEsON7PEcY95awR0AAAA with id 12031053
11 04 2016 13:47:17.060:WARN [web-server]: 404: /base/angular2/src/platform/browser/browser_adapter
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR: Error{stack: null, originalErr: Error{line: 2607, sourceURL: 'http://localhost:9876/base/node_modules/traceur/bin/traceur.js?acc944b759aac9f90a61020b0a5599a29040edfc', stack: 'idRejectHandler@http://localhost:9876/base/node_modules/traceur/bin/traceur.js?acc944b759aac9f90a61020b0a5599a29040edfc:2607:12
promiseHandle@http://localhost:9876/base/node_modules/traceur/bin/traceur.js?acc944b759aac9f90a61020b0a5599a29040edfc:2806:27
http://localhost:9876/base/node_modules/traceur/bin/traceur.js?acc944b759aac9f90a61020b0a5599a29040edfc:2800:22
flush@http://localhost:9876/base/node_modules/traceur/bin/traceur.js?acc944b759aac9f90a61020b0a5599a29040edfc:2556:15'}, line: 2607, sourceURL: 'http://localhost:9876/base/node_modules/traceur/bin/traceur.js?acc944b759aac9f90a61020b0a5599a29040edfc'}
```

**Comment by lathonez** [comment]
Hey,

Sorry for the delayed response, I've been away for a few days.

The modular structure you have should work fine. The 404 in your stack trace seems to be referring to `/base/angular2/src/platform/browser/browser_adapter` as opposed to any of your files in `./modules`

Few of questions:

* Is this an open source project (in which case I will be able to help you debug it easily)
* Have you managed to clone this repo and run the test suite against it?
* What is the contents of your `./www/build/test` folder after the build?

**Comment by lathonez** [comment]
I'm going to close this, just re-open it & get back to me if you're still facing issues.

Thanks.
