### ISSUE TITLE
No gulp filie found

### ISSUE THREAD

**Issue by yokeshvaradhan** [lathonez/clicker#74]
i am trying to test an app, i am able to test a sample starter app i followed the same procedure there i got an error
yokeshs-Mac-mini:~ yokesh$ node_modules/gulp/bin/gulp.js --gulpfile test/gulpfile.ts --cwd ./ test.build
[17:42:59] No gulpfile found

so i tried to install it manually

yokeshs-Mac-mini:~ yokesh$ sudo npm install gulp -g
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp/bin/gulp.js
gulp@3.9.1 /usr/local/lib/node_modules/gulp
├── interpret@1.0.0
├── pretty-hrtime@1.0.2
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── tildify@1.2.0 (os-homedir@1.0.1)
├── v8flags@2.0.11 (user-home@1.1.1)
├── semver@4.3.6
├── chalk@1.1.3 (supports-color@2.0.0, ansi-styles@2.2.1, escape-string-regexp@1.0.5, has-ansi@2.0.0, strip-ansi@3.0.1)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.2.1 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.2, findup-sync@0.3.0, resolve@1.1.7)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.3, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, vinyl@0.5.3, gulplog@1.0.0, through2@2.0.1, lodash.template@3.6.2, multipipe@0.1.2, dateformat@1.0.12)

but still i get the same error
yokeshs-Mac-mini:~ yokesh$ node_modules/gulp/bin/gulp.js --gulpfile test/gulpfile.ts --cwd ./ test.build
[17:44:25] No gulpfile found
yokeshs-Mac-mini:~ yokesh$

**Comment by lathonez** [comment]
The error is complaining about the lack of a gulpfile, not that gulp is not installed.

`[17:44:25] No gulpfile found`

run

`ls test/gulpfile.ts`

from your project's main working directory

**Comment by yokeshvaradhan** [comment]
i am having gulp file 
yokeshs-Mac-mini:easycloud yokesh$ ls test/gulpfile.ts
test/gulpfile.ts

but today i got another issue
yokeshs-Mac-mini:easycloud yokesh$ node_modules/gulp/bin/gulp.js --gulpfile test/gulpfile.ts --cwd ./ test.build
[07:55:55] Requiring external module ts-node/register
TSError: ⨯ Unable to compile TypeScript
app/pages/soLogin/business-partner-location.ts (5,22): Cannot find module './config'. (2307)
app/pages/soLogin/business-partner-location.ts (6,27): Cannot find module './user-service'. (2307)
node_modules/angular2/src/facade/promise.d.ts (1,10): Cannot re-export name that is not defined in the module. (2661)
    at getOutput (/Users/yokesh/easycloud/node_modules/ts-node/src/ts-node.ts:210:13)
    at Object.loader (/Users/yokesh/easycloud/node_modules/ts-node/src/ts-node.ts:225:23)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/Users/yokesh/easycloud/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/yokesh/easycloud/node_modules/liftoff/index.js:193:16)
    at module.exports (/Users/yokesh/easycloud/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/Users/yokesh/easycloud/node_modules/liftoff/index.js:185:9)
yokeshs-Mac-mini:easycloud yokesh$ ls test/gulpfile.ts

**Comment by lathonez** [comment]
I don't mean to be rude or dismissive, but perhaps it's better to try to work through the errors yourself rather than posting everything you get on here.

I am very happy to help people debug the testing framework but I'd appreciate it if you tried to solve the problems yourself first.
