### ISSUE TITLE
Can't test while using ionic-native

### ISSUE THREAD

**Issue by galvanu** [lathonez/clicker#78]
I'm using Ionic native package for cordova plugins. After adding the ionic-native the UT framework fails with the following error:
[web-server]: 404: /base/ionic-native.js

Looks like the ionic-native.js is not loaded into the browser.
I looked into your project and it looks like you also added the ionic-native package under package.json.
Don't you need to add anything else in karma-config?

**Comment by lathonez** [comment]
Ionic native comes with the ionic starter.

If you'd like to use it in testing see this issue:
https://github.com/lathonez/clicker/pull/66

which is your exact question.

The blog section "Testing External Modules" explains how to test external
modules. Also there's an FAQ with several other examples.
http://lathonez.github.io/2016/ionic-2-unit-testing/

Over the coming days I hope to remove the need for this but the work isn't
quite there yet.

**Comment by galvanu** [comment]
Thanks a lot, it solved my issue. 

One more question, did you try to use and test Rxjs? it looks like although all files are loaded into the browser an error still throws during the run sating the following:
TypeError: rxjs_1.ReplaySubject is not a constructor

(same happens if using Observable instead of ReplaySubject)

Thanks again for the contribution and for the quick reply.

**Comment by lathonez** [comment]
Glad to hear it solved your issue.

I have zero experience with rxjs, but would be happy to learn something new. I suggest waiting a day or two so I can get this new stuff merged in and then picking it up again. I'll be happy to help after that.

**Comment by galvanu** [comment]
I also working on it now, looks like I find the issue.
I'm new with github pull request but I'll try to create a pull request for rxjs dependency. If I don't succeed I'll publish it here.

**Comment by lathonez** [comment]
It's not worth doing a PR until my new changes are in.

**Comment by galvanu** [comment]
Ok so I'll wait for it.

**Comment by lathonez** [comment]
I might merge it tonight, working on it now..

**Comment by lathonez** [comment]
440ac08

**Comment by lathonez** [comment]
Open another / PR if you've anything to add, chur!
