### ISSUE TITLE
No provider for TestComponentBuilder

### ISSUE THREAD

**Issue by mbakker96** [lathonez/clicker#81]
Hi 

My project tests files are almost the same as the clickers project so I think this question can be asked here. (correct me if I'm wrong)

I want to do the same as in the clickerlist.spec.ts file. I want to fake a class because when I create a new settingsService class `settingsService = new settingsService()` it triggers the constructor and I want to mock that. 

This is what I saw in y[our code](https://github.com/lathonez/clicker/blob/master/app%2Fpages%2FclickerList%2FclickerList.spec.ts#L22-L56) and I want to to do that also in my class. 

But I get the error `Failed: No provider for TestComponentBuilder!` But don't know where to add that provider and could not find where you did it

This is  my unit test what I've so far:

```typescript
import {WrittenHoursPage}       from './written-hours';
import {SettingsService}        from '../../services/settings-service';
import {provide}                from 'angular2/core';
import {
    beforeEach,
    beforeEachProviders,
    ComponentFixture,
    injectAsync,
    TestComponentBuilder,
}                               from 'angular2/testing';
import {Utils} from '../../services/utils';

let writtenHoursPage: WrittenHoursPage        = null;
let writtenHoursPageFixture: ComponentFixture = null;

class MockClass {
    public getSelectedDate(): Date {
        return new Date(2016, 3, 15);
    }
}

export function main(): void {
    'use strict';

    describe('WrittenHours', () => {
        beforeEachProviders(() => [
            provide(SettingsService, {useClass: MockClass}),
        ]);

        beforeEach(injectAsync([TestComponentBuilder], (tcb: TestComponentBuilder) => {
            return tcb
                .createAsync(WrittenHoursPage)
                .then((componentFixture: ComponentFixture) => {
                    writtenHoursPageFixture = componentFixture;
                    writtenHoursPage        = componentFixture.componentInstance;
                    writtenHoursPageFixture.detectChanges();
                })
                .catch(Utils.promiseCatchHandler);
        }));

        it('initialize', () => {
            expect(writtenHoursPage).not.toBeNull();
        });

    });
}
```

**Comment by lathonez** [comment]
https://github.com/lathonez/clicker/blob/master/app/app.spec.ts#L6-L7

Also in the [blog](http://lathonez.github.io/2016/ionic-2-unit-testing/):

> Note the setBaseTestProviders line, enabling us to utilise Angular 2’s testing framework in our tests. 

You should have a read of [this blog](https://developers.livechatinc.com/blog/testing-angular-2-apps-dependency-injection-and-components)

**Comment by lathonez** [comment]
#191
