### ISSUE TITLE
Tests fail when run with phantomjs instead of Chrome

### ISSUE THREAD

**Issue by masimakopoulos** [lathonez/clicker#86]
I checked out 7dd49f8b9066946e3def3bd5e7453fdd20e9ef22 and run the tests locally and a lot of logs between tests about unhandled promise rejections and I get success for 13 out of 14. Changing browser to chrome passes all tests. 
Thought I should ask as Travis is only running against chrome and this would not show up right?

**Comment by lathonez** [comment]
Travis is using Chrome, but I use phantom locally and haven't seen anything.

I'll re-install everything and have a look.

**Comment by lathonez** [comment]
Also I'm not totally sure why we don't use Phantom (as well) in Travis. It's a relic of the ng2 seed fork. I'm sure there's a good reason.

FWIW I often find Phantom will decide to fail a bunch of tests through version changes.

**Comment by lathonez** [comment]
So everything runs for me using Phantom:

```
x220:~/code/clicker$ npm test

> clicker@1.1.0 test /home/lathonez/code/clicker
> gulp --gulpfile test/gulpfile.ts --cwd ./ unit-test

[09:28:30] Requiring external module ts-node/register
[09:28:33] sourced Ionic's gulpfile @ /home/lathonez/code/clicker/gulpfile.js
[09:28:33] Using gulpfile ~/code/clicker/test/gulpfile.ts
[09:28:33] Starting 'unit-test'...
[09:28:33] Starting 'clean-test'...
[09:28:33] Starting 'html'...
[09:28:33] Starting 'lint'...
[09:28:34] Starting 'patch-app'...
[09:28:34] node_modules/ionic-angular/decorators/app.js has been backed up to node_modules/ionic-angular/decorators/app.backup
[09:28:34] node_modules/ionic-angular/decorators/app.js has been patched with test/app.stub.js
[09:28:34] Finished 'patch-app' after 4.51 ms
[09:28:34] Deleted -
[09:28:34] Finished 'clean-test' after 59 ms
[09:28:34] Finished 'html' after 766 ms
[09:28:35] Finished 'lint' after 1.02 s
[09:28:35] Starting 'build-unit'...
[09:28:49] Starting 'restore-app'...
[09:28:49] node_modules/ionic-angular/decorators/app.backup has been restored to node_modules/ionic-angular/decorators/app.js
[09:28:49] Finished 'restore-app' after 2.16 ms
[09:28:49] Finished 'build-unit' after 14 s
[09:28:49] Starting 'karma'...

START:
27 04 2016 09:28:52.552:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
27 04 2016 09:28:52.559:INFO [launcher]: Starting browser PhantomJS
27 04 2016 09:28:52.802:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket /#bE1JHC4PHSUVtsmTAAAA with id 86652258
  ClickerApp
    ✔ initialises with two possible pages
    ✔ initialises with a root page
    ✔ initialises with an app
    ✔ opens a page
LOG: 'Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.'
  ClickerButton
    ✔ initialises
    ✔ displays the clicker name and count
    ✔ does a click
  ClickerForm
    ✔ initialises
    ✔ passes new clicker through to service
    ✔ doesn't try to add a clicker with no name
  Click
    ✔ initialises with defaults
    ✔ initialises with overrides
  Clicker
    ✔ initialises with the correct name
  ClickerList
    ✔ initialises
  Page2
    ✔ initialises
  Clickers
    ✔ initialises with empty clickers
    ✔ creates an instance of SqlStorage
    ✔ has empty ids with no storage
    ✔ has empty clickers with no storage
    ✔ can initialise a clicker from string
    ✔ returns undefined for a bad id
    ✔ adds a new clicker with the correct name
    ✔ removes a clicker by id
    ✔ does a click
    ✔ loads IDs from storage
    ✔ loads clickers from storage
  Utils
    ✔ resets a control

Finished in 3.714 secs / 1.606 secs

SUMMARY:
✔ 27 tests completed
[09:29:00] Finished 'karma' after 11 s
[09:29:00] Starting 'remap-coverage'...
[09:29:08] Finished 'remap-coverage' after 8.16 s
[09:29:08] Starting 'prune-coverage'...
[09:29:08] Finished 'prune-coverage' after 182 ms
[09:29:08] Starting 'report-coverage'...
-------------------------------|----------|----------|----------|----------|----------------|
File                           |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------------|----------|----------|----------|----------|----------------|
 app/                          |      100 |      100 |      100 |      100 |                |
  app.ts                       |      100 |      100 |      100 |      100 |                |
 app/components/clickerButton/ |      100 |      100 |      100 |      100 |                |
  clickerButton.ts             |      100 |      100 |      100 |      100 |                |
 app/components/clickerForm/   |      100 |      100 |      100 |      100 |                |
  clickerForm.ts               |      100 |      100 |      100 |      100 |                |
 app/models/                   |      100 |      100 |      100 |      100 |                |
  click.ts                     |      100 |      100 |      100 |      100 |                |
  clicker.ts                   |      100 |      100 |      100 |      100 |                |
 app/pages/clickerList/        |      100 |      100 |      100 |      100 |                |
  clickerList.ts               |      100 |      100 |      100 |      100 |                |
 app/pages/page2/              |      100 |      100 |      100 |      100 |                |
  page2.ts                     |      100 |      100 |      100 |      100 |                |
 app/services/                 |    95.18 |       50 |    92.59 |    95.89 |                |
  clickers.ts                  |    98.55 |       50 |      100 |    98.36 |             35 |
  utils.ts                     |    78.57 |      100 |       50 |    83.33 |           8,10 |
-------------------------------|----------|----------|----------|----------|----------------|
All files                      |    97.73 |     87.5 |    96.15 |    98.11 |                |
-------------------------------|----------|----------|----------|----------|----------------|

[09:29:08] Finished 'report-coverage' after 106 ms
[09:29:08] Finished 'unit-test' after 35 s
```

After a fresh clone and install

Is your package.json and dependencies all up to date. I'm going to put Phantom on travis now and see what happens

**Comment by lathonez** [comment]
https://travis-ci.org/lathonez/clicker/builds/125952998

seems fine

**Comment by masimakopoulos** [comment]
Yes, I have noticed in the past that phantom might fail for its own reasons, but wasn't sure if this time it was only happening to me or not and thought it was better to ask.

BTW here is the error I am getting on PhantomJS 2.1.1 (Mac OS X 0.0.0)]

```
RROR: 'EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error during instantiation of Clickers! (ClickerList -> Clickers).
ORIGINAL EXCEPTION: Error: SecurityError: DOM Exception 18
ORIGINAL STACKTRACE:
openDatabase@[native code]
SqlStorage@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:3840768
initStorage@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:62315
Clickers@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:56448
http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1750496
_instantiate@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1475769
_instantiateProvider@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1469509
_new@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1468710
getObjByKeyId@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1436384
_getByKeyDefault@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1485834
_getByKey@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1481905
_getByDependency@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1480715
_instantiate@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1471306
_instantiateProvider@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1469509
_new@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1468710
instantiateProvider@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1435057
init@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1629863
AppElement@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1554291
viewFactory_HostClickerList0
createHostViewInContainer@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1679831
createHostView@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1662145
http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:2958210
invoke@http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js?24f148375ef2f655790fd2c7cc5ac3dcfe4bf118:390:34
onInvoke@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1815779
invoke@http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js?24f148375ef2f655790fd2c7cc5ac3dcfe4bf118:389:43
run@http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js?24f148375ef2f655790fd2c7cc5ac3dcfe4bf118:283:50
http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js?24f148375ef2f655790fd2c7cc5ac3dcfe4bf118:635:61
invokeTask@http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js?24f148375ef2f655790fd2c7cc5ac3dcfe4bf118:423:43
onInvokeTask@http://localhost:9876/base/www/build/test/test.bundle.js?3bee4af27e37256a5ea73061df9cb12c38311e2c:9:1815387
invokeTask@http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js?24f148375ef2f655790fd2c7cc5ac3dcfe4bf118:422:55
runTask@http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js?24f148375ef2f655790fd2c7cc5ac3dcfe4bf118:320:58
drainMicroTaskQueue@http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js?24f148375ef2f655790fd2c7cc5ac3dcfe4bf118:541:43
invoke@http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.js?24f148375ef2f655790fd2c7cc5ac3dcfe4bf118:493:41
```

**Comment by masimakopoulos** [comment]
Could be a phantoms/macos thing. Could be random. Since it's passing travis I guess no point in researching this, unless more people have issues.

**Comment by lathonez** [comment]
Interesting. I had the exact same error on another project, with SQLStorage, only in Phantom.

It's definitely not MacOS, as I had it here on ubuntu 14.04.

That project is pretty big, and I switched from Phantom to Chrome a long time ago as I couldn't afford to debug Phantom all the time. I did a big upgrade and thought it would be cool if Phantom would work, but it doesn't so I still use Chrome for it.
 
If you ever find a solution to it please let me know, I'll do the same.

**Comment by lathonez** [comment]
Relevant: https://github.com/mozilla/localForage/issues/52

**Comment by wstidolph** [comment]
I get this error (ORIGINAL EXCEPTION: Error: SecurityError: DOM Exception 18)
on a fresh pull of clicker on 4 July 2016 (1e785c6e7134f609a913eaa68a878e973c347f43) on Windows 10, which causes the ClickerList "Initializes" test to fail inside the openDatabase/SqlStorage call. The call fails whether I run as normal or Adminstrator user. All tests pass using Chrome.

I don't know if this is relevant, but the error stack reports using PhantomJS 2.1.1, though I see the package.json requires "phantomjs-prebuilt": "2.1.7". It seems the phantomjs prebuilt includes phantom 2.1.1 in phantomjs-prebuilt/lib/bin/phantom.

**Comment by lathonez** [comment]
@wstidolph - thanks, this is useful. Unfortunately I have zero access to Windows 10.

I'll repoen this but I don't know how I'll be able to help in the short term.

**Comment by lathonez** [comment]
Might be worth trying to integrate with appveyor, they're using [windows server 2012](https://www.appveyor.com/docs/installed-software#operating-system) to build.

@wstidolph thoughts?

**Comment by wstidolph** [comment]
I'm out of my depth, just learning this tech stack (so, thanks for the great examples in 'clicker'!). One thing I notice is that your test-passing trace above includes a call to 'patch-app' after the 'lint' and my run doesn't have that in either the passing (Chrome) nor failing (PhantomJS) case - what's it do?

**Comment by lathonez** [comment]
Ah that's no longer a thing, we removed it in #79

**Comment by wstidolph** [comment]
re appveyor - well, it's free for OSS so that's good, and with the new linux subsystem coming in windows I anticipate a boost in the number of programmers using it as a dev platform, so that argues for it being good to validate on Windows. But this problem isn't Windows-specific, is it?

**Comment by lathonez** [comment]
Yeah I think I'll give appveyor a go when I have some time.

Re being windows specific, we've never been able to reproduce with this
project on Ubuntu (trusty or xenial) Arch 4.5.4 or macos (Yosemite).

@masimakopoulos <https://github.com/masimakopoulos> had the issue with this
project on macos.

I also know people have used this project on Windows without reporting the
error though I don't know what versions.

If we could provide a docker image based on Ubuntu would you be able to
give it a try?

**Comment by wstidolph** [comment]
Sure, I can spin up a docker image.

In the meantime, is there some way for me to collect more-useful information on Windows - do you know if there's verbosity flags etc that might get more info from SqlStorage about what's going wrong?

**Comment by lathonez** [comment]
We shouldn't be hitting `SQLStorage` at all, which is what makes the whole thing so strange.

For unit testing we're just interested in the input / output of our functions, not what `SQLStorage` is doing, so `SQLStorage` should be stubbed / mocked accordingly.

This is why we've got the storage init in it's own function `initStorage`: https://github.com/lathonez/clicker/blob/master/app/services/clickers.ts#L69-L71

In the unit tests, we create a mock and return that from the above function: https://github.com/lathonez/clicker/blob/master/app/services/clickers.spec.ts#L59

From what I've seen (on another project), this error is triggered on _import_ of `SQLStorage`: https://github.com/lathonez/clicker/blob/master/app/services/clickers.ts#L4

One thing we could / should try, is using dependency injection to provide the mock storage class to the clicker service spec. I have tried this on another project to address this error with no luck, but we know so little about what's going on here it's probably worth a go.

So three changes would be necessary:

* Use DI to pass `SQLStorage` in the constructor of Clickers (an example of this is in [app.ts](https://github.com/lathonez/clicker/blob/master/app/app.ts#L20))
* remove the `initStorage` function (referenced above) and initialise `SQLStorage` in the constructor of Clickers
* provide the mock `SQLStorage` class to the `Clickers` spec (see [diExports.ts](https://github.com/lathonez/clicker/blob/master/test/diExports.ts#L10-L16), an implementing [test spec](https://github.com/lathonez/clicker/blob/master/app/components/clickerForm/clickerForm.spec.ts#L22), and the [unifying blog post](http://lathonez.github.io/2016/unify-di-boilerplate/) for background)

Unless you'd feel comfortable making the changes I'd be happy to do them, they make sense / are good practice anyway. Then you'll be able to give it a go and see if you can still repro afterwards.

What do you think?

**Comment by wstidolph** [comment]
I'd be happy to do the testing, sure. I don't think I'd trust me quite yet
to implement your design :)



On Fri, Jul 8, 2016 at 6:20 PM, Stephen Hazleton <notifications@github.com>
wrote:

> We shouldn't be hitting SQLStorage at all, which is what makes the whole
> thing so strange.
>
> For unit testing we're just interested in the input / output of our
> functions, not what SQLStorage is doing, so SQLStorage should be stubbed
> / mocked accordingly.
>
> This is why we've got the storage init in it's own function initStorage:
> https://github.com/lathonez/clicker/blob/master/app/services/clickers.ts#L69-L71
>
> In the unit tests, we create a mock and return that from the above
> function:
> https://github.com/lathonez/clicker/blob/master/app/services/clickers.spec.ts#L59
>
> From what I've seen (on another project), this error is triggered on
> *import* of SQLStorage:
> https://github.com/lathonez/clicker/blob/master/app/services/clickers.ts#L4
>
> One thing we could / should try, is using dependency injection to provide
> the mock storage class to the clicker service spec. I have tried this on
> another project to address this error with no luck, but we know so little
> about what's going on here it's probably worth a go.
>
> So three changes would be necessary:
>
>    - Use DI to pass SQLStorage in the constructor of Clickers (an example
>    of this is in app.ts
>    <https://github.com/lathonez/clicker/blob/master/app/app.ts#L20>)
>    - remove the initStorage function (referenced above) and initialise
>    SQLStorage in the constructor of Clickers
>    - provide the mock SQLStorage class to the Clickers spec (see
>    diExports.ts
>    <https://github.com/lathonez/clicker/blob/master/test/diExports.ts#L10-L16>,
>    an implementing test spec
>    <https://github.com/lathonez/clicker/blob/master/app/components/clickerForm/clickerForm.spec.ts#L22>,
>    and the unifying blog post
>    <http://lathonez.github.io/2016/unify-di-boilerplate/> for background)
>
> Unless you'd feel comfortable making the changes I'd be happy to do them,
> they make sense / are good practice anyway. Then you'll be able to give it
> a go and see if you can still repro afterwards.
>
> What do you think?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lathonez/clicker/issues/86#issuecomment-231506326>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEAJHDv1xsyLKfY8qlTvAYq6ckWi4Gpks5qTvdjgaJpZM4IP4-s>
> .
>



-- 
  Wayne Stidolph  | (831) 419 7146 | LinkedIn
<http://www.linkedin.com/in/waynestidolph> | Google+
<https://google.com/+WayneStidolph> | twitter
<https://twitter.com/#!/wstidolph> | personal blog
<http://waynedge.blogspot.com/>

**Comment by lathonez** [comment]
OK thanks. I'll probably have some time for it tomorrow.

**Comment by wstidolph** [comment]
In case it helps ... I don't think it's the import statement. I tried leaving in the import statement in ```clickers.ts```, but just having ```initStorage()``` return without executing ```new SqlStorage``` and while the initializes test still fails, it's not the DOM Exception 18 any more, it's just ```undefined is not an object (evaluating '_this.storage.get')```

**Comment by lathonez** [comment]
That does help. Thanks. Hopefully we'll have some luck with this rewrite.

**Comment by lathonez** [comment]
@wstidolph any luck against those changes?

**Comment by wstidolph** [comment]
Well, it changed - but, not good. I did a clean checkout (none of my code), npm install, reboot, then:
```
START:
10 07 2016 14:32:53.907:INFO [framework.browserify]: bundle built
10 07 2016 14:32:53.941:INFO [karma]: Karma v1.1.0 server started at http://localhost:9876/
10 07 2016 14:32:53.942:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
10 07 2016 14:32:53.948:INFO [launcher]: Starting browser PhantomJS
10 07 2016 14:33:53.950:WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
10 07 2016 14:33:55.952:WARN [launcher]: PhantomJS was not killed in 2000 ms, sending SIGKILL.
10 07 2016 14:33:57.955:WARN [launcher]: PhantomJS was not killed by SIGKILL in 2000 ms, continuing.

Finished in 0 secs / 0 secs

[14:33:57] 'karma' errored after 1.32 min
```
In case it's relevant, I've verified getting the same result whether I have whether or not I have PhantomJS installed globally; but, when I install PhantomJS globally, I *can* start it and get to the phantomjs prompt.

Using Chrome, all tests still pass.

**Comment by lathonez** [comment]
When you say clean checkout you mean you cloned it fresh or...?

**Comment by wstidolph** [comment]
yes - freshly cloned 'clicker' from github, into an empty dir:
```
$ git log
commit 0d3f50ed35aff24dfcced56e82bae333104abe02
Author: Stephen Hazleton <shazleto@gmail.com>
Date:   Sun Jul 10 16:50:35 2016 +1000

    Forgot to bump package version [ci skip]
```
After the pm install and reboot, I ran from Windows 10 non-Administrator CMD prompt, and also tried using Cygwin bash (same result, no PhantomJS launch).

**Comment by lathonez** [comment]
If you roll back the changes the tests run giving the same results as
before?

**Comment by wstidolph** [comment]
Hmmm, no - so, I don't think my test taught us anything yet about your recent changes.

In the freshly-cloned project I rolled back to:
```
commit a7ce1e7a51265d5e4e73c4a3a9dcee220795dd5a
Author: Stephen Hazleton <shazleto@gmail.com>
Date:   Thu Jul 7 09:54:28 2016 +1000

    Import tslint rules from frontend
```
And I still get 'non-capture':
```
10 07 2016 16:27:32.206:INFO [launcher]: Starting browser PhantomJS
10 07 2016 16:28:32.208:WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
10 07 2016 16:28:34.210:WARN [launcher]: PhantomJS was not killed in 2000 ms, sending SIGKILL.
10 07 2016 16:28:36.213:WARN [launcher]: PhantomJS was not killed by SIGKILL in 2000 ms, continuing.
```
I opened my existing copy of clicker (the one I've been adding my own code to) and verified it still has the DOM Exception 18 problem even when I roll back to the same commit (95dd5a) so this isn't something related to my global setup - there's some difference between the two projects, apparently something not in git. I need to do some exploring to find out what that is before I can honestly do a test of the new code; I'll try directory compares and such tomorrow.

**Comment by lathonez** [comment]
OK thanks.

The odd thing is that it has still been running in Chrome this whole time.. My next step is going to be to integrate with appveyor, but I don't know when I will have time for this (I may do, just can't commit to anything at the moment / don't know how much work is involved). I also am not convinced that we'll see the issues there, though I hope we do.

With regard to debugging phantom on your current set up, I try to have as little installed globally as possible:

* you can be confident that your individual projects are using the versions they came bundled with
* it's easy to isolate projects (and different versions of the same project)

I have the following modules installed globally:

```
x220:~$ npm list -g --depth=0
/usr/lib
├── cordova@6.2.0
├── ionic@2.0.0-beta.32
├── npm@3.10.3
└── semver@5.2.0
```

Everything else comes with `clicker`.

Also I know you said you rebooteded in between tests, but I've seen a stray `karma` or `gulp` process cause this behaviour.

**Comment by wstidolph** [comment]
Thanks for the advice. Since I get different behavior from the two projects at the same git commit, I don't know how global things or stray processes could be responsible, but it's easy enough to fix mine up to be much closer to yours than it is now :)

**Comment by wstidolph** [comment]
Yay - you got it, all tests pass using PhantomJS!

You probably don't want the entire backstory :) but it came down to completely removing and reinstalling node (4.4.5), npm (3.10.5), and re-cloning 'clickers' again (old *.js and .map files were still sitting around, I guess they're not cleaned up by the typescript compiler?). But, now your project and my project built on top of it are able to test using PhantomJS, so there's a lot less screen-flashing going on :)

Thanks for 'clickers' and for the fix.

**Comment by lathonez** [comment]
> Yay - you got it, all tests pass using PhantomJS!

great news nice one!

> (old *.js and .map files were still sitting around, I guess they're not cleaned up by the typescript compiler?)

Hmm we should probably be hooking into Ionic's clean task as a pre-requisite to the Karma tasks.

> Thanks for 'clickers' and for the fix.

You're welcome thanks for helping getting to the bottom of it.

**Comment by lathonez** [comment]
https://github.com/lathonez/clicker/commit/1f25717c9b9c580416f0f2f2aa98c4df191e04d6

Hooking into Ionic's clean task before testing

**Comment by adneneBen** [comment]
Hello Everyone,

when i run tests in Chrome i got no error but for phantomJs i got this

`7:WARN [karma]: No captured browser, open http://localhost:9876/
17 06 2019 15:57:57.613:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
17 06 2019 15:57:57.613:INFO [launcher]: Launching browsers Chrome, PhantomJS with unlimited concurrency
17 06 2019 15:57:57.637:INFO [launcher]: Starting browser Chrome
17 06 2019 15:57:57.652:INFO [launcher]: Starting browser PhantomJS
17 06 2019 15:58:03.934:WARN [karma]: No captured browser, open http://localhost:9876/    
17 06 2019 15:58:04.165:INFO [Chrome 75.0.3770 (Linux 0.0.0)]: Connected on socket jAMsBKvRaZYNuYoeAAAA with id 96393824
17 06 2019 15:58:04.171:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket t95D3PSPHoBNo0zEAAAB with id 47837624
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Invalid character: '`'
  at http://localhost:9876/_karma_webpack_/main.js:4814
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Invalid character: '`'
  at http://localhost:9876/_karma_webpack_/main.js:4814

PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Invalid character: '`'
  at http://localhost:9876/_karma_webpack_/main.js:4814`

any idea please

Thank you
