### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by BugsBunnyBR** [lathonez/clicker#89]
It seems like there is no need to run
```
# npm run webdriver-update <- You will need to run this the first time
```
but the readme does not says how to install webdriver-update...so I think the readme should be updated.

**Comment by BugsBunnyBR** [comment]
@lathonez ,
Hey man, there is or there is not the need to webdriver-manager? postinstall references it...
```
"postinstall": "ionic state restore && typings install && webdriver-manager update && cp test/karma-static/*.html node_modules/karma/static",
```
if there is the need..how to install it?

**Comment by lathonez** [comment]
Comes with protractor

```
x220:~/code/clicker$ find . -name webdriver-manager
./node_modules/.bin/webdriver-manager
./node_modules/protractor/bin/webdriver-manager
```

**Comment by BugsBunnyBR** [comment]
Thanks for the explanation. :-D
