### ISSUE TITLE
Cloned project not work.

### ISSUE THREAD

**Issue by EugeneSnihovsky** [lathonez/clicker#91]
Hello! Thanks for the work you've done. I'm trying to run the application, but get an error. Maybe you know what the problem is?

**Step to reproduce:**
1. git clone https://github.com/lathonez/clicker.git
2. cd clicker
3. npm install
4. npm start (also try ionic serve)
Got an error (npm-debug.log):

> 0 info it worked if it ends with ok
1 verbose cli [ '/opt/node/bin/node', '/opt/node/bin/npm', 'start' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle clicker@1.2.0~prestart: clicker@1.2.0
6 silly lifecycle clicker@1.2.0~prestart: no script for prestart, continuing
7 info lifecycle clicker@1.2.0~start: clicker@1.2.0
8 verbose lifecycle clicker@1.2.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle clicker@1.2.0~start: PATH: /opt/node/lib/node_modules/npm/bin/node-gyp-bin:/home/maniak/projects/clicker/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/android-sdk/tools:/opt/android-sdk/platform-tools:/opt/node/bin:/opt/gradle/bin
10 verbose lifecycle clicker@1.2.0~start: CWD: /home/maniak/projects/clicker
11 silly lifecycle clicker@1.2.0~start: Args: [ '-c', 'ionic serve' ]
12 silly lifecycle clicker@1.2.0~start: Returned: code: 1  signal: null
13 info lifecycle clicker@1.2.0~start: Failed to exec start script
14 verbose stack Error: clicker@1.2.0 start: `ionic serve`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/opt/node/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/opt/node/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid clicker@1.2.0
16 verbose cwd /home/maniak/projects/clicker
17 error Linux 3.16.0-38-generic
18 error argv "/opt/node/bin/node" "/opt/node/bin/npm" "start"
19 error node v5.3.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error clicker@1.2.0 start: `ionic serve`
22 error Exit status 1
23 error Failed at the clicker@1.2.0 start script 'ionic serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the clicker package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic serve
23 error You can get their info via:
23 error     npm owner ls clicker
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Bash error**

> Error: Cannot find module '/home/maniak/projects/clicker/ionic.config.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.run (/opt/node/lib/node_modules/ionic/lib/cli.js:131:20)
    at Object.<anonymous> (/opt/node/lib/node_modules/ionic/bin/ionic:13:10)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

Also try **npm run reinstall**, but got an error
npm ERR! missing script: reinstall

**Ionic info**

> Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Distributor ID:     LinuxMint Description:  Linux Mint 17.2 Rafaela 
Node Version: v5.3.0

**Comment by lathonez** [comment]
You probably need to update ionic globally?

**Comment by EugeneSnihovsky** [comment]
Update to Ionic CLI Version: 2.0.0-beta.25 and everything started to to work.
Thanks :)
