### ISSUE TITLE
Reflect.js is included twice in index.html

### ISSUE THREAD

**Issue by masimakopoulos** [lathonez/clicker#96]
Not sure if this is by mistake or is intentional but Reflect.js is included twice in current index.html on line [24](https://github.com/lathonez/clicker/blob/master/www/index.html#L24) and line [26](https://github.com/lathonez/clicker/blob/master/www/index.html#L26)

**Comment by lathonez** [comment]
Definitely by mistake. Bad merge in from the Ionic tutorial app.

thanks for the heads up.
